##
## This file is part of the libopencm3 project.
##
## This library is free software: you can redistribute it and/or modify
## it under the terms of the GNU Lesser General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This library is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Lesser General Public License for more details.
##
## You should have received a copy of the GNU Lesser General Public License
## along with this library.  If not, see <http://www.gnu.org/licenses/>.
##

BOARD = efm32hg309-generic
PROJECT = usb-gadget0-$(BOARD)
BUILD_DIR = bin-$(BOARD)

SHARED_DIR = ../shared

CFILES = main-$(BOARD).c
CFILES += usb-gadget0.c
CFILES += delay_efm32.c

VPATH += $(SHARED_DIR)

INCLUDES += $(patsubst %,-I%, . $(SHARED_DIR))

OPENCM3_DIR=../..

### This section can go to an arch shared rules eventually...
LDSCRIPT = ../../lib/efm32/hg/efm32hg309f64.ld
OPENCM3_LIB = opencm3_efm32hg
OPENCM3_DEFS = -DEFM32HG
FP_FLAGS ?= -mfloat-abi=soft
ARCH_FLAGS = -mthumb -mcpu=cortex-m0plus $(FP_FLAGS)
#OOCD_INTERFACE = stlink-v2-1
#OOCD_TARGET = efm32
OOCD_FILE = openocd.efm32hg309-generic.cfg

include ../rules.mk
