##
## This file is part of the libopencm3 project.
##
## This library is free software: you can redistribute it and/or modify
## it under the terms of the GNU Lesser General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This library is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Lesser General Public License for more details.
##
## You should have received a copy of the GNU Lesser General Public License
## along with this library.  If not, see <http://www.gnu.org/licenses/>.
##

BOARD = stm32l053disco
PROJECT = usb-gadget0-$(BOARD)
BUILD_DIR = bin-$(BOARD)

SHARED_DIR = ../shared

CFILES = main-$(BOARD).c
CFILES += usb-gadget0.c

VPATH += $(SHARED_DIR)

INCLUDES += $(patsubst %,-I%, . $(SHARED_DIR))

OPENCM3_DIR=../..

### This section can go to an arch shared rules eventually...
LDSCRIPT = ../../lib/stm32/l0/stm32l0xx8.ld
OPENCM3_LIB = opencm3_stm32l0
OPENCM3_DEFS = -DSTM32L0
#FP_FLAGS ?= -mfloat-abi=hard -mfpu=fpv4-sp-d16
ARCH_FLAGS = -mthumb -mcpu=cortex-m0plus $(FP_FLAGS)
#OOCD_INTERFACE = stlink-v2-1
#OOCD_TARGET = stm32l0
OOCD_FILE = openocd.stm32l053disco.cfg

include ../rules.mk
