##
## This file is part of the libopencm3 project.
##
## This library is free software: you can redistribute it and/or modify
## it under the terms of the GNU Lesser General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This library is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Lesser General Public License for more details.
##
## You should have received a copy of the GNU Lesser General Public License
## along with this library.  If not, see <http://www.gnu.org/licenses/>.
##

BOARD = stm32l1-generic
PROJECT = usb-gadget0-$(BOARD)
BUILD_DIR = bin-$(BOARD)

SHARED_DIR = ../shared

CFILES = main-$(BOARD).c
CFILES += usb-gadget0.c trace.c trace_stdio.c
CFILES += delay.c

VPATH += $(SHARED_DIR)

INCLUDES += $(patsubst %,-I%, . $(SHARED_DIR))

OPENCM3_DIR=../..

### This section can go to an arch shared rules eventually...
LDSCRIPT = ../../lib/stm32/l1/stm32l15xxb.ld
OPENCM3_LIB = opencm3_stm32l1
OPENCM3_DEFS = -DSTM32L1
ARCH_FLAGS = -mthumb -mcpu=cortex-m3
#OOCD_INTERFACE = jlink
#OOCD_TARGET = stm32l1x
OOCD_FILE = openocd.stm32l1-generic.cfg

include ../rules.mk
