/* This file is part of the libopencm3 project.
 *
 * It was generated by the irq2nvic_h script.
 *
 * These definitions bend every interrupt handler that is defined CMSIS style
 * to the weak symbol exported by libopencm3.
 */

#define WWDG_IRQHandler wwdg_isr
#define PVD_IRQHandler pvd_isr
#define RTC_IRQHandler rtc_isr
#define FLASH_IRQHandler flash_isr
#define RCC_IRQHandler rcc_isr
#define EXTI0_1_IRQHandler exti0_1_isr
#define EXTI2_3_IRQHandler exti2_3_isr
#define EXTI4_15_IRQHandler exti4_15_isr
#define RESERVED_8_IRQHandler reserved_8_isr
#define DMA1_CHANNEL1_IRQHandler dma1_channel1_isr
#define DMA1_CHANNEL2_3_IRQHandler dma1_channel2_3_isr
#define RESERVED_11_IRQHandler reserved_11_isr
#define ADC_COMP_IRQHandler adc_comp_isr
#define TIM1_BRK_UP_TRG_COM_IRQHandler tim1_brk_up_trg_com_isr
#define TIM1_CC_IRQHandler tim1_cc_isr
#define RESERVED_15_IRQHandler reserved_15_isr
#define TIM3_IRQHandler tim3_isr
#define LPTIM1_IRQHandler lptim1_isr
#define RESERVED_18_IRQHandler reserved_18_isr
#define TIM14_IRQHandler tim14_isr
#define RESERVED_20_IRQHandler reserved_20_isr
#define TIM16_IRQHandler tim16_isr
#define TIM17_IRQHandler tim17_isr
#define I2C1_IRQHandler i2c1_isr
#define RESERVED_24_IRQHandler reserved_24_isr
#define SPI1_IRQHandler spi1_isr
#define RESERVED_26_IRQHandler reserved_26_isr
#define USART1_IRQHandler usart1_isr
#define USART2_IRQHandler usart2_isr
