/** @addtogroup gpio_defines
 *
 * @author @htmlonly &copy; @endhtmlonly 2018
 * Gerrit Maus <funk@maus.xyz>, Luong Le <novercy@live.com>
 *
 */
/*
 * This file is part of the libopencm3 project.
 *
 * Copyright (C) 2018 Gerrit Maus <funk@maus.xyz>, Luong Le <novercy@live.com>
 *
 * This library is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library.  If not, see <http://www.gnu.org/licenses/>.
 */

/* THIS FILE SHOULD NOT BE INCLUDED DIRECTLY, BUT ONLY VIA GPIO.H
The order of header inclusion is important. gpio.h includes the device
specific memorymap.h header before including this header file.*/

/** @cond */
#if defined(LIBOPENCM3_GPIO_H)
/** @endcond */
#ifndef LIBOPENCM3_GPIO_COMMON_H
#define LIBOPENCM3_GPIO_COMMON_H

/**@{*/

/** @defgroup gpio_registers GPIO Registers
 * @ingroup gpio_defines
 * @brief GPIO Registers
@{*/

/* --------------------- GPIO registers for NRF52 -------------------------- */

/* Registers */
#define GPIO_OUT                       MMIO32((GPIO_BASE) + 0x504)
#define GPIO_OUTSET                    MMIO32((GPIO_BASE) + 0x508)
#define GPIO_OUTCLR                    MMIO32((GPIO_BASE) + 0x50C)
#define GPIO_IN                        MMIO32((GPIO_BASE) + 0x510)
#define GPIO_DIR                       MMIO32((GPIO_BASE) + 0x514)
#define GPIO_DIRSET                    MMIO32((GPIO_BASE) + 0x518)
#define GPIO_DIRCLR                    MMIO32((GPIO_BASE) + 0x51C)
#define GPIO_LATCH                     MMIO32((GPIO_BASE) + 0x520)
#define GPIO_DETECTMODE                MMIO32((GPIO_BASE) + 0x524)
#define GPIO_PIN_CNF                   PTRIO32((GPIO_BASE) + 0x700)
/**@}*/

/* --- GPIO_OUT values ----------------------------------------------------- */

#define GPIO_OUT_PIN(n)                  (1 << n)
/** @defgroup gpio_out Write GPIO port
@ingroup gpio_defines
@{*/
#define GPIO_OUT_PIN0_LOW                (0 << 0)
#define GPIO_OUT_PIN0_Low                (0 << 0)
#define GPIO_OUT_PIN0_HIGH               (1 << 0)
#define GPIO_OUT_PIN0_High               (1 << 0)
#define GPIO_OUT_PIN1_LOW                (0 << 1)
#define GPIO_OUT_PIN1_Low                (0 << 1)
#define GPIO_OUT_PIN1_HIGH               (1 << 1)
#define GPIO_OUT_PIN1_High               (1 << 1)
#define GPIO_OUT_PIN2_LOW                (0 << 2)
#define GPIO_OUT_PIN2_Low                (0 << 2)
#define GPIO_OUT_PIN2_HIGH               (1 << 2)
#define GPIO_OUT_PIN2_High               (1 << 2)
#define GPIO_OUT_PIN3_LOW                (0 << 3)
#define GPIO_OUT_PIN3_Low                (0 << 3)
#define GPIO_OUT_PIN3_HIGH               (1 << 3)
#define GPIO_OUT_PIN3_High               (1 << 3)
#define GPIO_OUT_PIN4_LOW                (0 << 4)
#define GPIO_OUT_PIN4_Low                (0 << 4)
#define GPIO_OUT_PIN4_HIGH               (1 << 4)
#define GPIO_OUT_PIN4_High               (1 << 4)
#define GPIO_OUT_PIN5_LOW                (0 << 5)
#define GPIO_OUT_PIN5_Low                (0 << 5)
#define GPIO_OUT_PIN5_HIGH               (1 << 5)
#define GPIO_OUT_PIN5_High               (1 << 5)
#define GPIO_OUT_PIN6_LOW                (0 << 6)
#define GPIO_OUT_PIN6_Low                (0 << 6)
#define GPIO_OUT_PIN6_HIGH               (1 << 6)
#define GPIO_OUT_PIN6_High               (1 << 6)
#define GPIO_OUT_PIN7_LOW                (0 << 7)
#define GPIO_OUT_PIN7_Low                (0 << 7)
#define GPIO_OUT_PIN7_HIGH               (1 << 7)
#define GPIO_OUT_PIN7_High               (1 << 7)
#define GPIO_OUT_PIN8_LOW                (0 << 8)
#define GPIO_OUT_PIN8_Low                (0 << 8)
#define GPIO_OUT_PIN8_HIGH               (1 << 8)
#define GPIO_OUT_PIN8_High               (1 << 8)
#define GPIO_OUT_PIN9_LOW                (0 << 9)
#define GPIO_OUT_PIN9_Low                (0 << 9)
#define GPIO_OUT_PIN9_HIGH               (1 << 9)
#define GPIO_OUT_PIN9_High               (1 << 9)
#define GPIO_OUT_PIN10_LOW               (0 << 10)
#define GPIO_OUT_PIN10_Low               (0 << 10)
#define GPIO_OUT_PIN10_HIGH              (1 << 10)
#define GPIO_OUT_PIN10_High              (1 << 10)
#define GPIO_OUT_PIN11_LOW               (0 << 11)
#define GPIO_OUT_PIN11_Low               (0 << 11)
#define GPIO_OUT_PIN11_HIGH              (1 << 11)
#define GPIO_OUT_PIN11_High              (1 << 11)
#define GPIO_OUT_PIN12_LOW               (0 << 12)
#define GPIO_OUT_PIN12_Low               (0 << 12)
#define GPIO_OUT_PIN12_HIGH              (1 << 12)
#define GPIO_OUT_PIN12_High              (1 << 12)
#define GPIO_OUT_PIN13_LOW               (0 << 13)
#define GPIO_OUT_PIN13_Low               (0 << 13)
#define GPIO_OUT_PIN13_HIGH              (1 << 13)
#define GPIO_OUT_PIN13_High              (1 << 13)
#define GPIO_OUT_PIN14_LOW               (0 << 14)
#define GPIO_OUT_PIN14_Low               (0 << 14)
#define GPIO_OUT_PIN14_HIGH              (1 << 14)
#define GPIO_OUT_PIN14_High              (1 << 14)
#define GPIO_OUT_PIN15_LOW               (0 << 15)
#define GPIO_OUT_PIN15_Low               (0 << 15)
#define GPIO_OUT_PIN15_HIGH              (1 << 15)
#define GPIO_OUT_PIN15_High              (1 << 15)
#define GPIO_OUT_PIN16_LOW               (0 << 16)
#define GPIO_OUT_PIN16_Low               (0 << 16)
#define GPIO_OUT_PIN16_HIGH              (1 << 16)
#define GPIO_OUT_PIN16_High              (1 << 16)
#define GPIO_OUT_PIN17_LOW               (0 << 17)
#define GPIO_OUT_PIN17_Low               (0 << 17)
#define GPIO_OUT_PIN17_HIGH              (1 << 17)
#define GPIO_OUT_PIN17_High              (1 << 17)
#define GPIO_OUT_PIN18_LOW               (0 << 18)
#define GPIO_OUT_PIN18_Low               (0 << 18)
#define GPIO_OUT_PIN18_HIGH              (1 << 18)
#define GPIO_OUT_PIN18_High              (1 << 18)
#define GPIO_OUT_PIN19_LOW               (0 << 19)
#define GPIO_OUT_PIN19_Low               (0 << 19)
#define GPIO_OUT_PIN19_HIGH              (1 << 19)
#define GPIO_OUT_PIN19_High              (1 << 19)
#define GPIO_OUT_PIN20_LOW               (0 << 20)
#define GPIO_OUT_PIN20_Low               (0 << 20)
#define GPIO_OUT_PIN20_HIGH              (1 << 20)
#define GPIO_OUT_PIN20_High              (1 << 20)
#define GPIO_OUT_PIN21_LOW               (0 << 21)
#define GPIO_OUT_PIN21_Low               (0 << 21)
#define GPIO_OUT_PIN21_HIGH              (1 << 21)
#define GPIO_OUT_PIN21_High              (1 << 21)
#define GPIO_OUT_PIN22_LOW               (0 << 22)
#define GPIO_OUT_PIN22_Low               (0 << 22)
#define GPIO_OUT_PIN22_HIGH              (1 << 22)
#define GPIO_OUT_PIN22_High              (1 << 22)
#define GPIO_OUT_PIN23_LOW               (0 << 23)
#define GPIO_OUT_PIN23_Low               (0 << 23)
#define GPIO_OUT_PIN23_HIGH              (1 << 23)
#define GPIO_OUT_PIN23_High              (1 << 23)
#define GPIO_OUT_PIN24_LOW               (0 << 24)
#define GPIO_OUT_PIN24_Low               (0 << 24)
#define GPIO_OUT_PIN24_HIGH              (1 << 24)
#define GPIO_OUT_PIN24_High              (1 << 24)
#define GPIO_OUT_PIN25_LOW               (0 << 25)
#define GPIO_OUT_PIN25_Low               (0 << 25)
#define GPIO_OUT_PIN25_HIGH              (1 << 25)
#define GPIO_OUT_PIN25_High              (1 << 25)
#define GPIO_OUT_PIN26_LOW               (0 << 26)
#define GPIO_OUT_PIN26_Low               (0 << 26)
#define GPIO_OUT_PIN26_HIGH              (1 << 26)
#define GPIO_OUT_PIN26_High              (1 << 26)
#define GPIO_OUT_PIN27_LOW               (0 << 27)
#define GPIO_OUT_PIN27_Low               (0 << 27)
#define GPIO_OUT_PIN27_HIGH              (1 << 27)
#define GPIO_OUT_PIN27_High              (1 << 27)
#define GPIO_OUT_PIN28_LOW               (0 << 28)
#define GPIO_OUT_PIN28_Low               (0 << 28)
#define GPIO_OUT_PIN28_HIGH              (1 << 28)
#define GPIO_OUT_PIN28_High              (1 << 28)
#define GPIO_OUT_PIN29_LOW               (0 << 29)
#define GPIO_OUT_PIN29_Low               (0 << 29)
#define GPIO_OUT_PIN29_HIGH              (1 << 29)
#define GPIO_OUT_PIN29_High              (1 << 29)
#define GPIO_OUT_PIN30_LOW               (0 << 30)
#define GPIO_OUT_PIN30_Low               (0 << 30)
#define GPIO_OUT_PIN30_HIGH              (1 << 30)
#define GPIO_OUT_PIN30_High              (1 << 30)
#define GPIO_OUT_PIN31_LOW               (0 << 31)
#define GPIO_OUT_PIN31_Low               (0 << 31)
#define GPIO_OUT_PIN31_HIGH              (1 << 31)
#define GPIO_OUT_PIN31_High              (1 << 31)
/**@}*/

/* --- GPIO_OUTSET values -------------------------------------------------- */

#define GPIO_OUTSET_PIN(n)                 (1 << n)
/** @defgroup gpio_outset Set individual bits in GPIO port
@ingroup gpio_defines
@{*/
#define GPIO_OUTSET_PIN0_SET               (1 << 0)
#define GPIO_OUTSET_PIN0_Set               (1 << 0)
#define GPIO_OUTSET_PIN1_SET               (1 << 1)
#define GPIO_OUTSET_PIN1_Set               (1 << 1)
#define GPIO_OUTSET_PIN2_SET               (1 << 2)
#define GPIO_OUTSET_PIN2_Set               (1 << 2)
#define GPIO_OUTSET_PIN3_SET               (1 << 3)
#define GPIO_OUTSET_PIN3_Set               (1 << 3)
#define GPIO_OUTSET_PIN4_SET               (1 << 4)
#define GPIO_OUTSET_PIN4_Set               (1 << 4)
#define GPIO_OUTSET_PIN5_SET               (1 << 5)
#define GPIO_OUTSET_PIN5_Set               (1 << 5)
#define GPIO_OUTSET_PIN6_SET               (1 << 6)
#define GPIO_OUTSET_PIN6_Set               (1 << 6)
#define GPIO_OUTSET_PIN7_SET               (1 << 7)
#define GPIO_OUTSET_PIN7_Set               (1 << 7)
#define GPIO_OUTSET_PIN8_SET               (1 << 8)
#define GPIO_OUTSET_PIN8_Set               (1 << 8)
#define GPIO_OUTSET_PIN9_SET               (1 << 9)
#define GPIO_OUTSET_PIN9_Set               (1 << 9)
#define GPIO_OUTSET_PIN10_SET              (1 << 10)
#define GPIO_OUTSET_PIN10_Set              (1 << 10)
#define GPIO_OUTSET_PIN11_SET              (1 << 11)
#define GPIO_OUTSET_PIN11_Set              (1 << 11)
#define GPIO_OUTSET_PIN12_SET              (1 << 12)
#define GPIO_OUTSET_PIN12_Set              (1 << 12)
#define GPIO_OUTSET_PIN13_SET              (1 << 13)
#define GPIO_OUTSET_PIN13_Set              (1 << 13)
#define GPIO_OUTSET_PIN14_SET              (1 << 14)
#define GPIO_OUTSET_PIN14_Set              (1 << 14)
#define GPIO_OUTSET_PIN15_SET              (1 << 15)
#define GPIO_OUTSET_PIN15_Set              (1 << 15)
#define GPIO_OUTSET_PIN16_SET              (1 << 16)
#define GPIO_OUTSET_PIN16_Set              (1 << 16)
#define GPIO_OUTSET_PIN17_SET              (1 << 17)
#define GPIO_OUTSET_PIN17_Set              (1 << 17)
#define GPIO_OUTSET_PIN18_SET              (1 << 18)
#define GPIO_OUTSET_PIN18_Set              (1 << 18)
#define GPIO_OUTSET_PIN19_SET              (1 << 19)
#define GPIO_OUTSET_PIN19_Set              (1 << 19)
#define GPIO_OUTSET_PIN20_SET              (1 << 20)
#define GPIO_OUTSET_PIN20_Set              (1 << 20)
#define GPIO_OUTSET_PIN21_SET              (1 << 21)
#define GPIO_OUTSET_PIN21_Set              (1 << 21)
#define GPIO_OUTSET_PIN22_SET              (1 << 22)
#define GPIO_OUTSET_PIN22_Set              (1 << 22)
#define GPIO_OUTSET_PIN23_SET              (1 << 23)
#define GPIO_OUTSET_PIN23_Set              (1 << 23)
#define GPIO_OUTSET_PIN24_SET              (1 << 24)
#define GPIO_OUTSET_PIN24_Set              (1 << 24)
#define GPIO_OUTSET_PIN25_SET              (1 << 25)
#define GPIO_OUTSET_PIN25_Set              (1 << 25)
#define GPIO_OUTSET_PIN26_SET              (1 << 26)
#define GPIO_OUTSET_PIN26_Set              (1 << 26)
#define GPIO_OUTSET_PIN27_SET              (1 << 27)
#define GPIO_OUTSET_PIN27_Set              (1 << 27)
#define GPIO_OUTSET_PIN28_SET              (1 << 28)
#define GPIO_OUTSET_PIN28_Set              (1 << 28)
#define GPIO_OUTSET_PIN29_SET              (1 << 29)
#define GPIO_OUTSET_PIN29_Set              (1 << 29)
#define GPIO_OUTSET_PIN30_SET              (1 << 30)
#define GPIO_OUTSET_PIN30_Set              (1 << 30)
#define GPIO_OUTSET_PIN31_SET              (1 << 31)
#define GPIO_OUTSET_PIN31_Set              (1 << 31)
/**@}*/

/* --- GPIO_OUTCLR values -------------------------------------------------- */

#define GPIO_OUTCLR_PIN(n)                   (1 << n)
/** @defgroup gpio_outclr Clear individual bits in GPIO port
@ingroup gpio_defines
@{*/
#define GPIO_OUTCLR_PIN0_CLEAR               (1 << 0)
#define GPIO_OUTCLR_PIN0_Clear               (1 << 0)
#define GPIO_OUTCLR_PIN1_CLEAR               (1 << 1)
#define GPIO_OUTCLR_PIN1_Clear               (1 << 1)
#define GPIO_OUTCLR_PIN2_CLEAR               (1 << 2)
#define GPIO_OUTCLR_PIN2_Clear               (1 << 2)
#define GPIO_OUTCLR_PIN3_CLEAR               (1 << 3)
#define GPIO_OUTCLR_PIN3_Clear               (1 << 3)
#define GPIO_OUTCLR_PIN4_CLEAR               (1 << 4)
#define GPIO_OUTCLR_PIN4_Clear               (1 << 4)
#define GPIO_OUTCLR_PIN5_CLEAR               (1 << 5)
#define GPIO_OUTCLR_PIN5_Clear               (1 << 5)
#define GPIO_OUTCLR_PIN6_CLEAR               (1 << 6)
#define GPIO_OUTCLR_PIN6_Clear               (1 << 6)
#define GPIO_OUTCLR_PIN7_CLEAR               (1 << 7)
#define GPIO_OUTCLR_PIN7_Clear               (1 << 7)
#define GPIO_OUTCLR_PIN8_CLEAR               (1 << 8)
#define GPIO_OUTCLR_PIN8_Clear               (1 << 8)
#define GPIO_OUTCLR_PIN9_CLEAR               (1 << 9)
#define GPIO_OUTCLR_PIN9_Clear               (1 << 9)
#define GPIO_OUTCLR_PIN10_CLEAR              (1 << 10)
#define GPIO_OUTCLR_PIN10_Clear              (1 << 10)
#define GPIO_OUTCLR_PIN11_CLEAR              (1 << 11)
#define GPIO_OUTCLR_PIN11_Clear              (1 << 11)
#define GPIO_OUTCLR_PIN12_CLEAR              (1 << 12)
#define GPIO_OUTCLR_PIN12_Clear              (1 << 12)
#define GPIO_OUTCLR_PIN13_CLEAR              (1 << 13)
#define GPIO_OUTCLR_PIN13_Clear              (1 << 13)
#define GPIO_OUTCLR_PIN14_CLEAR              (1 << 14)
#define GPIO_OUTCLR_PIN14_Clear              (1 << 14)
#define GPIO_OUTCLR_PIN15_CLEAR              (1 << 15)
#define GPIO_OUTCLR_PIN15_Clear              (1 << 15)
#define GPIO_OUTCLR_PIN16_CLEAR              (1 << 16)
#define GPIO_OUTCLR_PIN16_Clear              (1 << 16)
#define GPIO_OUTCLR_PIN17_CLEAR              (1 << 17)
#define GPIO_OUTCLR_PIN17_Clear              (1 << 17)
#define GPIO_OUTCLR_PIN18_CLEAR              (1 << 18)
#define GPIO_OUTCLR_PIN18_Clear              (1 << 18)
#define GPIO_OUTCLR_PIN19_CLEAR              (1 << 19)
#define GPIO_OUTCLR_PIN19_Clear              (1 << 19)
#define GPIO_OUTCLR_PIN20_CLEAR              (1 << 20)
#define GPIO_OUTCLR_PIN20_Clear              (1 << 20)
#define GPIO_OUTCLR_PIN21_CLEAR              (1 << 21)
#define GPIO_OUTCLR_PIN21_Clear              (1 << 21)
#define GPIO_OUTCLR_PIN22_CLEAR              (1 << 22)
#define GPIO_OUTCLR_PIN22_Clear              (1 << 22)
#define GPIO_OUTCLR_PIN23_CLEAR              (1 << 23)
#define GPIO_OUTCLR_PIN23_Clear              (1 << 23)
#define GPIO_OUTCLR_PIN24_CLEAR              (1 << 24)
#define GPIO_OUTCLR_PIN24_Clear              (1 << 24)
#define GPIO_OUTCLR_PIN25_CLEAR              (1 << 25)
#define GPIO_OUTCLR_PIN25_Clear              (1 << 25)
#define GPIO_OUTCLR_PIN26_CLEAR              (1 << 26)
#define GPIO_OUTCLR_PIN26_Clear              (1 << 26)
#define GPIO_OUTCLR_PIN27_CLEAR              (1 << 27)
#define GPIO_OUTCLR_PIN27_Clear              (1 << 27)
#define GPIO_OUTCLR_PIN28_CLEAR              (1 << 28)
#define GPIO_OUTCLR_PIN28_Clear              (1 << 28)
#define GPIO_OUTCLR_PIN29_CLEAR              (1 << 29)
#define GPIO_OUTCLR_PIN29_Clear              (1 << 29)
#define GPIO_OUTCLR_PIN30_CLEAR              (1 << 30)
#define GPIO_OUTCLR_PIN30_Clear              (1 << 30)
#define GPIO_OUTCLR_PIN31_CLEAR              (1 << 31)
#define GPIO_OUTCLR_PIN31_Clear              (1 << 31)
/**@}*/

/* --- GPIO_IN values ------------------------------------------------------ */

#define GPIO_IN_PIN(n)             (1 << n)
/** @defgroup gpio_in Read GPIO port
@ingroup gpio_defines
@{*/
#define GPIO_IN_PIN0               (1 << 0)
#define GPIO_IN_PIN1               (1 << 1)
#define GPIO_IN_PIN2               (1 << 2)
#define GPIO_IN_PIN3               (1 << 3)
#define GPIO_IN_PIN4               (1 << 4)
#define GPIO_IN_PIN5               (1 << 5)
#define GPIO_IN_PIN6               (1 << 6)
#define GPIO_IN_PIN7               (1 << 7)
#define GPIO_IN_PIN8               (1 << 8)
#define GPIO_IN_PIN9               (1 << 9)
#define GPIO_IN_PIN10              (1 << 10)
#define GPIO_IN_PIN11              (1 << 11)
#define GPIO_IN_PIN12              (1 << 12)
#define GPIO_IN_PIN13              (1 << 13)
#define GPIO_IN_PIN14              (1 << 14)
#define GPIO_IN_PIN15              (1 << 15)
#define GPIO_IN_PIN16              (1 << 16)
#define GPIO_IN_PIN17              (1 << 17)
#define GPIO_IN_PIN18              (1 << 18)
#define GPIO_IN_PIN19              (1 << 19)
#define GPIO_IN_PIN20              (1 << 20)
#define GPIO_IN_PIN21              (1 << 21)
#define GPIO_IN_PIN22              (1 << 22)
#define GPIO_IN_PIN23              (1 << 23)
#define GPIO_IN_PIN24              (1 << 24)
#define GPIO_IN_PIN25              (1 << 25)
#define GPIO_IN_PIN26              (1 << 26)
#define GPIO_IN_PIN27              (1 << 27)
#define GPIO_IN_PIN28              (1 << 28)
#define GPIO_IN_PIN29              (1 << 29)
#define GPIO_IN_PIN30              (1 << 30)
#define GPIO_IN_PIN31              (1 << 31)
/**@}*/

/* --- GPIO_DIR values ----------------------------------------------------- */

#define GPIO_DIR_PIN(n)                    (1 << n)
/** @defgroup gpio_dir Direction of GPIO pins
@ingroup gpio_defines
@{*/
#define GPIO_DIR_PIN0_INPUT                (0 << 0)
#define GPIO_DIR_PIN0_Input                (0 << 0)
#define GPIO_DIR_PIN0_OUTPUT               (1 << 0)
#define GPIO_DIR_PIN0_Output               (1 << 0)
#define GPIO_DIR_PIN1_INPUT                (0 << 1)
#define GPIO_DIR_PIN1_Input                (0 << 1)
#define GPIO_DIR_PIN1_OUTPUT               (1 << 1)
#define GPIO_DIR_PIN1_Output               (1 << 1)
#define GPIO_DIR_PIN2_INPUT                (0 << 2)
#define GPIO_DIR_PIN2_Input                (0 << 2)
#define GPIO_DIR_PIN2_OUTPUT               (1 << 2)
#define GPIO_DIR_PIN2_Output               (1 << 2)
#define GPIO_DIR_PIN3_INPUT                (0 << 3)
#define GPIO_DIR_PIN3_Input                (0 << 3)
#define GPIO_DIR_PIN3_OUTPUT               (1 << 3)
#define GPIO_DIR_PIN3_Output               (1 << 3)
#define GPIO_DIR_PIN4_INPUT                (0 << 4)
#define GPIO_DIR_PIN4_Input                (0 << 4)
#define GPIO_DIR_PIN4_OUTPUT               (1 << 4)
#define GPIO_DIR_PIN4_Output               (1 << 4)
#define GPIO_DIR_PIN5_INPUT                (0 << 5)
#define GPIO_DIR_PIN5_Input                (0 << 5)
#define GPIO_DIR_PIN5_OUTPUT               (1 << 5)
#define GPIO_DIR_PIN5_Output               (1 << 5)
#define GPIO_DIR_PIN6_INPUT                (0 << 6)
#define GPIO_DIR_PIN6_Input                (0 << 6)
#define GPIO_DIR_PIN6_OUTPUT               (1 << 6)
#define GPIO_DIR_PIN6_Output               (1 << 6)
#define GPIO_DIR_PIN7_INPUT                (0 << 7)
#define GPIO_DIR_PIN7_Input                (0 << 7)
#define GPIO_DIR_PIN7_OUTPUT               (1 << 7)
#define GPIO_DIR_PIN7_Output               (1 << 7)
#define GPIO_DIR_PIN8_INPUT                (0 << 8)
#define GPIO_DIR_PIN8_Input                (0 << 8)
#define GPIO_DIR_PIN8_OUTPUT               (1 << 8)
#define GPIO_DIR_PIN8_Output               (1 << 8)
#define GPIO_DIR_PIN9_INPUT                (0 << 9)
#define GPIO_DIR_PIN9_Input                (0 << 9)
#define GPIO_DIR_PIN9_OUTPUT               (1 << 9)
#define GPIO_DIR_PIN9_Output               (1 << 9)
#define GPIO_DIR_PIN10_INPUT               (0 << 10)
#define GPIO_DIR_PIN10_Input               (0 << 10)
#define GPIO_DIR_PIN10_OUTPUT              (1 << 10)
#define GPIO_DIR_PIN10_Output              (1 << 10)
#define GPIO_DIR_PIN11_INPUT               (0 << 11)
#define GPIO_DIR_PIN11_Input               (0 << 11)
#define GPIO_DIR_PIN11_OUTPUT              (1 << 11)
#define GPIO_DIR_PIN11_Output              (1 << 11)
#define GPIO_DIR_PIN12_INPUT               (0 << 12)
#define GPIO_DIR_PIN12_Input               (0 << 12)
#define GPIO_DIR_PIN12_OUTPUT              (1 << 12)
#define GPIO_DIR_PIN12_Output              (1 << 12)
#define GPIO_DIR_PIN13_INPUT               (0 << 13)
#define GPIO_DIR_PIN13_Input               (0 << 13)
#define GPIO_DIR_PIN13_OUTPUT              (1 << 13)
#define GPIO_DIR_PIN13_Output              (1 << 13)
#define GPIO_DIR_PIN14_INPUT               (0 << 14)
#define GPIO_DIR_PIN14_Input               (0 << 14)
#define GPIO_DIR_PIN14_OUTPUT              (1 << 14)
#define GPIO_DIR_PIN14_Output              (1 << 14)
#define GPIO_DIR_PIN15_INPUT               (0 << 15)
#define GPIO_DIR_PIN15_Input               (0 << 15)
#define GPIO_DIR_PIN15_OUTPUT              (1 << 15)
#define GPIO_DIR_PIN15_Output              (1 << 15)
#define GPIO_DIR_PIN16_INPUT               (0 << 16)
#define GPIO_DIR_PIN16_Input               (0 << 16)
#define GPIO_DIR_PIN16_OUTPUT              (1 << 16)
#define GPIO_DIR_PIN16_Output              (1 << 16)
#define GPIO_DIR_PIN17_INPUT               (0 << 17)
#define GPIO_DIR_PIN17_Input               (0 << 17)
#define GPIO_DIR_PIN17_OUTPUT              (1 << 17)
#define GPIO_DIR_PIN17_Output              (1 << 17)
#define GPIO_DIR_PIN18_INPUT               (0 << 18)
#define GPIO_DIR_PIN18_Input               (0 << 18)
#define GPIO_DIR_PIN18_OUTPUT              (1 << 18)
#define GPIO_DIR_PIN18_Output              (1 << 18)
#define GPIO_DIR_PIN19_INPUT               (0 << 19)
#define GPIO_DIR_PIN19_Input               (0 << 19)
#define GPIO_DIR_PIN19_OUTPUT              (1 << 19)
#define GPIO_DIR_PIN19_Output              (1 << 19)
#define GPIO_DIR_PIN20_INPUT               (0 << 20)
#define GPIO_DIR_PIN20_Input               (0 << 20)
#define GPIO_DIR_PIN20_OUTPUT              (1 << 20)
#define GPIO_DIR_PIN20_Output              (1 << 20)
#define GPIO_DIR_PIN21_INPUT               (0 << 21)
#define GPIO_DIR_PIN21_Input               (0 << 21)
#define GPIO_DIR_PIN21_OUTPUT              (1 << 21)
#define GPIO_DIR_PIN21_Output              (1 << 21)
#define GPIO_DIR_PIN22_INPUT               (0 << 22)
#define GPIO_DIR_PIN22_Input               (0 << 22)
#define GPIO_DIR_PIN22_OUTPUT              (1 << 22)
#define GPIO_DIR_PIN22_Output              (1 << 22)
#define GPIO_DIR_PIN23_INPUT               (0 << 23)
#define GPIO_DIR_PIN23_Input               (0 << 23)
#define GPIO_DIR_PIN23_OUTPUT              (1 << 23)
#define GPIO_DIR_PIN23_Output              (1 << 23)
#define GPIO_DIR_PIN24_INPUT               (0 << 24)
#define GPIO_DIR_PIN24_Input               (0 << 24)
#define GPIO_DIR_PIN24_OUTPUT              (1 << 24)
#define GPIO_DIR_PIN24_Output              (1 << 24)
#define GPIO_DIR_PIN25_INPUT               (0 << 25)
#define GPIO_DIR_PIN25_Input               (0 << 25)
#define GPIO_DIR_PIN25_OUTPUT              (1 << 25)
#define GPIO_DIR_PIN25_Output              (1 << 25)
#define GPIO_DIR_PIN26_INPUT               (0 << 26)
#define GPIO_DIR_PIN26_Input               (0 << 26)
#define GPIO_DIR_PIN26_OUTPUT              (1 << 26)
#define GPIO_DIR_PIN26_Output              (1 << 26)
#define GPIO_DIR_PIN27_INPUT               (0 << 27)
#define GPIO_DIR_PIN27_Input               (0 << 27)
#define GPIO_DIR_PIN27_OUTPUT              (1 << 27)
#define GPIO_DIR_PIN27_Output              (1 << 27)
#define GPIO_DIR_PIN28_INPUT               (0 << 28)
#define GPIO_DIR_PIN28_Input               (0 << 28)
#define GPIO_DIR_PIN28_OUTPUT              (1 << 28)
#define GPIO_DIR_PIN28_Output              (1 << 28)
#define GPIO_DIR_PIN29_INPUT               (0 << 29)
#define GPIO_DIR_PIN29_Input               (0 << 29)
#define GPIO_DIR_PIN29_OUTPUT              (1 << 29)
#define GPIO_DIR_PIN29_Output              (1 << 29)
#define GPIO_DIR_PIN30_INPUT               (0 << 30)
#define GPIO_DIR_PIN30_Input               (0 << 30)
#define GPIO_DIR_PIN30_OUTPUT              (1 << 30)
#define GPIO_DIR_PIN30_Output              (1 << 30)
#define GPIO_DIR_PIN31_INPUT               (0 << 31)
#define GPIO_DIR_PIN31_Input               (0 << 31)
#define GPIO_DIR_PIN31_OUTPUT              (1 << 31)
#define GPIO_DIR_PIN31_Output              (1 << 31)
/**@}*/

/* --- GPIO_DIRSET values -------------------------------------------------- */

#define GPIO_DIRSET_PIN(n)                 (1 << n)
/** @defgroup gpio_dirset Set direction of individual GPIO pins
@ingroup gpio_defines
@{*/
#define GPIO_DIRSET_PIN0_SET               (1 << 0)
#define GPIO_DIRSET_PIN0_Set               (1 << 0)
#define GPIO_DIRSET_PIN1_SET               (1 << 1)
#define GPIO_DIRSET_PIN1_Set               (1 << 1)
#define GPIO_DIRSET_PIN2_SET               (1 << 2)
#define GPIO_DIRSET_PIN2_Set               (1 << 2)
#define GPIO_DIRSET_PIN3_SET               (1 << 3)
#define GPIO_DIRSET_PIN3_Set               (1 << 3)
#define GPIO_DIRSET_PIN4_SET               (1 << 4)
#define GPIO_DIRSET_PIN4_Set               (1 << 4)
#define GPIO_DIRSET_PIN5_SET               (1 << 5)
#define GPIO_DIRSET_PIN5_Set               (1 << 5)
#define GPIO_DIRSET_PIN6_SET               (1 << 6)
#define GPIO_DIRSET_PIN6_Set               (1 << 6)
#define GPIO_DIRSET_PIN7_SET               (1 << 7)
#define GPIO_DIRSET_PIN7_Set               (1 << 7)
#define GPIO_DIRSET_PIN8_SET               (1 << 8)
#define GPIO_DIRSET_PIN8_Set               (1 << 8)
#define GPIO_DIRSET_PIN9_SET               (1 << 9)
#define GPIO_DIRSET_PIN9_Set               (1 << 9)
#define GPIO_DIRSET_PIN10_SET              (1 << 10)
#define GPIO_DIRSET_PIN10_Set              (1 << 10)
#define GPIO_DIRSET_PIN11_SET              (1 << 11)
#define GPIO_DIRSET_PIN11_Set              (1 << 11)
#define GPIO_DIRSET_PIN12_SET              (1 << 12)
#define GPIO_DIRSET_PIN12_Set              (1 << 12)
#define GPIO_DIRSET_PIN13_SET              (1 << 13)
#define GPIO_DIRSET_PIN13_Set              (1 << 13)
#define GPIO_DIRSET_PIN14_SET              (1 << 14)
#define GPIO_DIRSET_PIN14_Set              (1 << 14)
#define GPIO_DIRSET_PIN15_SET              (1 << 15)
#define GPIO_DIRSET_PIN15_Set              (1 << 15)
#define GPIO_DIRSET_PIN16_SET              (1 << 16)
#define GPIO_DIRSET_PIN16_Set              (1 << 16)
#define GPIO_DIRSET_PIN17_SET              (1 << 17)
#define GPIO_DIRSET_PIN17_Set              (1 << 17)
#define GPIO_DIRSET_PIN18_SET              (1 << 18)
#define GPIO_DIRSET_PIN18_Set              (1 << 18)
#define GPIO_DIRSET_PIN19_SET              (1 << 19)
#define GPIO_DIRSET_PIN19_Set              (1 << 19)
#define GPIO_DIRSET_PIN20_SET              (1 << 20)
#define GPIO_DIRSET_PIN20_Set              (1 << 20)
#define GPIO_DIRSET_PIN21_SET              (1 << 21)
#define GPIO_DIRSET_PIN21_Set              (1 << 21)
#define GPIO_DIRSET_PIN22_SET              (1 << 22)
#define GPIO_DIRSET_PIN22_Set              (1 << 22)
#define GPIO_DIRSET_PIN23_SET              (1 << 23)
#define GPIO_DIRSET_PIN23_Set              (1 << 23)
#define GPIO_DIRSET_PIN24_SET              (1 << 24)
#define GPIO_DIRSET_PIN24_Set              (1 << 24)
#define GPIO_DIRSET_PIN25_SET              (1 << 25)
#define GPIO_DIRSET_PIN25_Set              (1 << 25)
#define GPIO_DIRSET_PIN26_SET              (1 << 26)
#define GPIO_DIRSET_PIN26_Set              (1 << 26)
#define GPIO_DIRSET_PIN27_SET              (1 << 27)
#define GPIO_DIRSET_PIN27_Set              (1 << 27)
#define GPIO_DIRSET_PIN28_SET              (1 << 28)
#define GPIO_DIRSET_PIN28_Set              (1 << 28)
#define GPIO_DIRSET_PIN29_SET              (1 << 29)
#define GPIO_DIRSET_PIN29_Set              (1 << 29)
#define GPIO_DIRSET_PIN30_SET              (1 << 30)
#define GPIO_DIRSET_PIN30_Set              (1 << 30)
#define GPIO_DIRSET_PIN31_SET              (1 << 31)
#define GPIO_DIRSET_PIN31_Set              (1 << 31)
/**@}*/

/* --- GPIO_DIRCLR values -------------------------------------------------- */

#define GPIO_DIRCLR_PIN(n)                   (1 << n)
/** @defgroup gpio_dirclr Clear direction of individual GPIO pins
@ingroup gpio_defines
@{*/
#define GPIO_DIRCLR_PIN0_CLEAR               (1 << 0)
#define GPIO_DIRCLR_PIN0_Clear               (1 << 0)
#define GPIO_DIRCLR_PIN1_CLEAR               (1 << 1)
#define GPIO_DIRCLR_PIN1_Clear               (1 << 1)
#define GPIO_DIRCLR_PIN2_CLEAR               (1 << 2)
#define GPIO_DIRCLR_PIN2_Clear               (1 << 2)
#define GPIO_DIRCLR_PIN3_CLEAR               (1 << 3)
#define GPIO_DIRCLR_PIN3_Clear               (1 << 3)
#define GPIO_DIRCLR_PIN4_CLEAR               (1 << 4)
#define GPIO_DIRCLR_PIN4_Clear               (1 << 4)
#define GPIO_DIRCLR_PIN5_CLEAR               (1 << 5)
#define GPIO_DIRCLR_PIN5_Clear               (1 << 5)
#define GPIO_DIRCLR_PIN6_CLEAR               (1 << 6)
#define GPIO_DIRCLR_PIN6_Clear               (1 << 6)
#define GPIO_DIRCLR_PIN7_CLEAR               (1 << 7)
#define GPIO_DIRCLR_PIN7_Clear               (1 << 7)
#define GPIO_DIRCLR_PIN8_CLEAR               (1 << 8)
#define GPIO_DIRCLR_PIN8_Clear               (1 << 8)
#define GPIO_DIRCLR_PIN9_CLEAR               (1 << 9)
#define GPIO_DIRCLR_PIN9_Clear               (1 << 9)
#define GPIO_DIRCLR_PIN10_CLEAR              (1 << 10)
#define GPIO_DIRCLR_PIN10_Clear              (1 << 10)
#define GPIO_DIRCLR_PIN11_CLEAR              (1 << 11)
#define GPIO_DIRCLR_PIN11_Clear              (1 << 11)
#define GPIO_DIRCLR_PIN12_CLEAR              (1 << 12)
#define GPIO_DIRCLR_PIN12_Clear              (1 << 12)
#define GPIO_DIRCLR_PIN13_CLEAR              (1 << 13)
#define GPIO_DIRCLR_PIN13_Clear              (1 << 13)
#define GPIO_DIRCLR_PIN14_CLEAR              (1 << 14)
#define GPIO_DIRCLR_PIN14_Clear              (1 << 14)
#define GPIO_DIRCLR_PIN15_CLEAR              (1 << 15)
#define GPIO_DIRCLR_PIN15_Clear              (1 << 15)
#define GPIO_DIRCLR_PIN16_CLEAR              (1 << 16)
#define GPIO_DIRCLR_PIN16_Clear              (1 << 16)
#define GPIO_DIRCLR_PIN17_CLEAR              (1 << 17)
#define GPIO_DIRCLR_PIN17_Clear              (1 << 17)
#define GPIO_DIRCLR_PIN18_CLEAR              (1 << 18)
#define GPIO_DIRCLR_PIN18_Clear              (1 << 18)
#define GPIO_DIRCLR_PIN19_CLEAR              (1 << 19)
#define GPIO_DIRCLR_PIN19_Clear              (1 << 19)
#define GPIO_DIRCLR_PIN20_CLEAR              (1 << 20)
#define GPIO_DIRCLR_PIN20_Clear              (1 << 20)
#define GPIO_DIRCLR_PIN21_CLEAR              (1 << 21)
#define GPIO_DIRCLR_PIN21_Clear              (1 << 21)
#define GPIO_DIRCLR_PIN22_CLEAR              (1 << 22)
#define GPIO_DIRCLR_PIN22_Clear              (1 << 22)
#define GPIO_DIRCLR_PIN23_CLEAR              (1 << 23)
#define GPIO_DIRCLR_PIN23_Clear              (1 << 23)
#define GPIO_DIRCLR_PIN24_CLEAR              (1 << 24)
#define GPIO_DIRCLR_PIN24_Clear              (1 << 24)
#define GPIO_DIRCLR_PIN25_CLEAR              (1 << 25)
#define GPIO_DIRCLR_PIN25_Clear              (1 << 25)
#define GPIO_DIRCLR_PIN26_CLEAR              (1 << 26)
#define GPIO_DIRCLR_PIN26_Clear              (1 << 26)
#define GPIO_DIRCLR_PIN27_CLEAR              (1 << 27)
#define GPIO_DIRCLR_PIN27_Clear              (1 << 27)
#define GPIO_DIRCLR_PIN28_CLEAR              (1 << 28)
#define GPIO_DIRCLR_PIN28_Clear              (1 << 28)
#define GPIO_DIRCLR_PIN29_CLEAR              (1 << 29)
#define GPIO_DIRCLR_PIN29_Clear              (1 << 29)
#define GPIO_DIRCLR_PIN30_CLEAR              (1 << 30)
#define GPIO_DIRCLR_PIN30_Clear              (1 << 30)
#define GPIO_DIRCLR_PIN31_CLEAR              (1 << 31)
#define GPIO_DIRCLR_PIN31_Clear              (1 << 31)
/**@}*/

/* --- GPIO_LATCH values --------------------------------------------------- */

#define GPIO_LATCH_PIN(n)                         (1 << n)
/** @defgroup gpio_latch Indicating what GPIO pins that have met the 
criteria set in the PIN_CNF[n].SENSE registers
@ingroup gpio_defines
@{*/
#define GPIO_LATCH_PIN0_NOTLATCHED                (0 << 0)
#define GPIO_LATCH_PIN0_NotLatched                (0 << 0)
#define GPIO_LATCH_PIN0_LATCHED                   (1 << 0)
#define GPIO_LATCH_PIN0_Latched                   (1 << 0)
#define GPIO_LATCH_PIN1_NOTLATCHED                (0 << 1)
#define GPIO_LATCH_PIN1_NotLatched                (0 << 1)
#define GPIO_LATCH_PIN1_LATCHED                   (1 << 1)
#define GPIO_LATCH_PIN1_Latched                   (1 << 1)
#define GPIO_LATCH_PIN2_NOTLATCHED                (0 << 2)
#define GPIO_LATCH_PIN2_NotLatched                (0 << 2)
#define GPIO_LATCH_PIN2_LATCHED                   (1 << 2)
#define GPIO_LATCH_PIN2_Latched                   (1 << 2)
#define GPIO_LATCH_PIN3_NOTLATCHED                (0 << 3)
#define GPIO_LATCH_PIN3_NotLatched                (0 << 3)
#define GPIO_LATCH_PIN3_LATCHED                   (1 << 3)
#define GPIO_LATCH_PIN3_Latched                   (1 << 3)
#define GPIO_LATCH_PIN4_NOTLATCHED                (0 << 4)
#define GPIO_LATCH_PIN4_NotLatched                (0 << 4)
#define GPIO_LATCH_PIN4_LATCHED                   (1 << 4)
#define GPIO_LATCH_PIN4_Latched                   (1 << 4)
#define GPIO_LATCH_PIN5_NOTLATCHED                (0 << 5)
#define GPIO_LATCH_PIN5_NotLatched                (0 << 5)
#define GPIO_LATCH_PIN5_LATCHED                   (1 << 5)
#define GPIO_LATCH_PIN5_Latched                   (1 << 5)
#define GPIO_LATCH_PIN6_NOTLATCHED                (0 << 6)
#define GPIO_LATCH_PIN6_NotLatched                (0 << 6)
#define GPIO_LATCH_PIN6_LATCHED                   (1 << 6)
#define GPIO_LATCH_PIN6_Latched                   (1 << 6)
#define GPIO_LATCH_PIN7_NOTLATCHED                (0 << 7)
#define GPIO_LATCH_PIN7_NotLatched                (0 << 7)
#define GPIO_LATCH_PIN7_LATCHED                   (1 << 7)
#define GPIO_LATCH_PIN7_Latched                   (1 << 7)
#define GPIO_LATCH_PIN8_NOTLATCHED                (0 << 8)
#define GPIO_LATCH_PIN8_NotLatched                (0 << 8)
#define GPIO_LATCH_PIN8_LATCHED                   (1 << 8)
#define GPIO_LATCH_PIN8_Latched                   (1 << 8)
#define GPIO_LATCH_PIN9_NOTLATCHED                (0 << 9)
#define GPIO_LATCH_PIN9_NotLatched                (0 << 9)
#define GPIO_LATCH_PIN9_LATCHED                   (1 << 9)
#define GPIO_LATCH_PIN9_Latched                   (1 << 9)
#define GPIO_LATCH_PIN10_NOTLATCHED               (0 << 10)
#define GPIO_LATCH_PIN10_NotLatched               (0 << 10)
#define GPIO_LATCH_PIN10_LATCHED                  (1 << 10)
#define GPIO_LATCH_PIN10_Latched                  (1 << 10)
#define GPIO_LATCH_PIN11_NOTLATCHED               (0 << 11)
#define GPIO_LATCH_PIN11_NotLatched               (0 << 11)
#define GPIO_LATCH_PIN11_LATCHED                  (1 << 11)
#define GPIO_LATCH_PIN11_Latched                  (1 << 11)
#define GPIO_LATCH_PIN12_NOTLATCHED               (0 << 12)
#define GPIO_LATCH_PIN12_NotLatched               (0 << 12)
#define GPIO_LATCH_PIN12_LATCHED                  (1 << 12)
#define GPIO_LATCH_PIN12_Latched                  (1 << 12)
#define GPIO_LATCH_PIN13_NOTLATCHED               (0 << 13)
#define GPIO_LATCH_PIN13_NotLatched               (0 << 13)
#define GPIO_LATCH_PIN13_LATCHED                  (1 << 13)
#define GPIO_LATCH_PIN13_Latched                  (1 << 13)
#define GPIO_LATCH_PIN14_NOTLATCHED               (0 << 14)
#define GPIO_LATCH_PIN14_NotLatched               (0 << 14)
#define GPIO_LATCH_PIN14_LATCHED                  (1 << 14)
#define GPIO_LATCH_PIN14_Latched                  (1 << 14)
#define GPIO_LATCH_PIN15_NOTLATCHED               (0 << 15)
#define GPIO_LATCH_PIN15_NotLatched               (0 << 15)
#define GPIO_LATCH_PIN15_LATCHED                  (1 << 15)
#define GPIO_LATCH_PIN15_Latched                  (1 << 15)
#define GPIO_LATCH_PIN16_NOTLATCHED               (0 << 16)
#define GPIO_LATCH_PIN16_NotLatched               (0 << 16)
#define GPIO_LATCH_PIN16_LATCHED                  (1 << 16)
#define GPIO_LATCH_PIN16_Latched                  (1 << 16)
#define GPIO_LATCH_PIN17_NOTLATCHED               (0 << 17)
#define GPIO_LATCH_PIN17_NotLatched               (0 << 17)
#define GPIO_LATCH_PIN17_LATCHED                  (1 << 17)
#define GPIO_LATCH_PIN17_Latched                  (1 << 17)
#define GPIO_LATCH_PIN18_NOTLATCHED               (0 << 18)
#define GPIO_LATCH_PIN18_NotLatched               (0 << 18)
#define GPIO_LATCH_PIN18_LATCHED                  (1 << 18)
#define GPIO_LATCH_PIN18_Latched                  (1 << 18)
#define GPIO_LATCH_PIN19_NOTLATCHED               (0 << 19)
#define GPIO_LATCH_PIN19_NotLatched               (0 << 19)
#define GPIO_LATCH_PIN19_LATCHED                  (1 << 19)
#define GPIO_LATCH_PIN19_Latched                  (1 << 19)
#define GPIO_LATCH_PIN20_NOTLATCHED               (0 << 20)
#define GPIO_LATCH_PIN20_NotLatched               (0 << 20)
#define GPIO_LATCH_PIN20_LATCHED                  (1 << 20)
#define GPIO_LATCH_PIN20_Latched                  (1 << 20)
#define GPIO_LATCH_PIN21_NOTLATCHED               (0 << 21)
#define GPIO_LATCH_PIN21_NotLatched               (0 << 21)
#define GPIO_LATCH_PIN21_LATCHED                  (1 << 21)
#define GPIO_LATCH_PIN21_Latched                  (1 << 21)
#define GPIO_LATCH_PIN22_NOTLATCHED               (0 << 22)
#define GPIO_LATCH_PIN22_NotLatched               (0 << 22)
#define GPIO_LATCH_PIN22_LATCHED                  (1 << 22)
#define GPIO_LATCH_PIN22_Latched                  (1 << 22)
#define GPIO_LATCH_PIN23_NOTLATCHED               (0 << 23)
#define GPIO_LATCH_PIN23_NotLatched               (0 << 23)
#define GPIO_LATCH_PIN23_LATCHED                  (1 << 23)
#define GPIO_LATCH_PIN23_Latched                  (1 << 23)
#define GPIO_LATCH_PIN24_NOTLATCHED               (0 << 24)
#define GPIO_LATCH_PIN24_NotLatched               (0 << 24)
#define GPIO_LATCH_PIN24_LATCHED                  (1 << 24)
#define GPIO_LATCH_PIN24_Latched                  (1 << 24)
#define GPIO_LATCH_PIN25_NOTLATCHED               (0 << 25)
#define GPIO_LATCH_PIN25_NotLatched               (0 << 25)
#define GPIO_LATCH_PIN25_LATCHED                  (1 << 25)
#define GPIO_LATCH_PIN25_Latched                  (1 << 25)
#define GPIO_LATCH_PIN26_NOTLATCHED               (0 << 26)
#define GPIO_LATCH_PIN26_NotLatched               (0 << 26)
#define GPIO_LATCH_PIN26_LATCHED                  (1 << 26)
#define GPIO_LATCH_PIN26_Latched                  (1 << 26)
#define GPIO_LATCH_PIN27_NOTLATCHED               (0 << 27)
#define GPIO_LATCH_PIN27_NotLatched               (0 << 27)
#define GPIO_LATCH_PIN27_LATCHED                  (1 << 27)
#define GPIO_LATCH_PIN27_Latched                  (1 << 27)
#define GPIO_LATCH_PIN28_NOTLATCHED               (0 << 28)
#define GPIO_LATCH_PIN28_NotLatched               (0 << 28)
#define GPIO_LATCH_PIN28_LATCHED                  (1 << 28)
#define GPIO_LATCH_PIN28_Latched                  (1 << 28)
#define GPIO_LATCH_PIN29_NOTLATCHED               (0 << 29)
#define GPIO_LATCH_PIN29_NotLatched               (0 << 29)
#define GPIO_LATCH_PIN29_LATCHED                  (1 << 29)
#define GPIO_LATCH_PIN29_Latched                  (1 << 29)
#define GPIO_LATCH_PIN30_NOTLATCHED               (0 << 30)
#define GPIO_LATCH_PIN30_NotLatched               (0 << 30)
#define GPIO_LATCH_PIN30_LATCHED                  (1 << 30)
#define GPIO_LATCH_PIN30_Latched                  (1 << 30)
#define GPIO_LATCH_PIN31_NOTLATCHED               (0 << 31)
#define GPIO_LATCH_PIN31_NotLatched               (0 << 31)
#define GPIO_LATCH_PIN31_LATCHED                  (1 << 31)
#define GPIO_LATCH_PIN31_Latched                  (1 << 31)
/**@}*/

/* --- GPIO_DETECTMODE values ---------------------------------------------- */

/** @defgroup gpio_detectmode Select mode for signal behaviour
@ingroup gpio_defines
@{*/
#define GPIO_DETECTMODE_DETECTMODE_DEFAULT        (0)
#define GPIO_DETECTMODE_DETECTMODE_Default        (0)
#define GPIO_DETECTMODE_DETECTMODE_LDETECT        (1)
/**@}*/

/* --- GPIO_PIN_CNF[n] values ---------------------------------------------- */

/** @defgroup gpio_pin_cnf[n] Configuration of GPIO pins
@ingroup gpio_defines
@{*/
/* Pin direction */
#define DIR_INPUT                              (0)
#define DIR_OUTPUT                             (1)
#define GPIO_PIN_CNF_DIR(n)                    (((n)&0x01) << 0)
#define GPIO_PIN_CNF_DIR_INPUT                 (0 << 0)
#define GPIO_PIN_CNF_DIR_Input                 (0 << 0)
#define GPIO_PIN_CNF_DIR_OUTPUT                (1 << 0)
#define GPIO_PIN_CNF_DIR_Output                (1 << 0)
/* Input buffer configuration */
#define INPUT_CONNECT                          (0)
#define INPUT_DISCONNECT                       (1)
#define GPIO_PIN_CNF_INPUT(n)                  (((n)&0x01) << 1)
#define GPIO_PIN_CNF_INPUT_CONNECT             (0 << 1)
#define GPIO_PIN_CNF_INPUT_Connect             (0 << 1)
#define GPIO_PIN_CNF_INPUT_DISCONNECT          (1 << 1)
#define GPIO_PIN_CNF_INPUT_Disconnect          (1 << 1)
/* Pull configuration */
#define PULL_DISABLED                          (0)
#define PULL_DOWN                              (1)
#define PULL_UP                                (3)
#define GPIO_PIN_CNF_PULL(n)                   (((n)&0x03) << 2)
#define GPIO_PIN_CNF_PULL_DISABLED             (0 << 2)
#define GPIO_PIN_CNF_PULL_Disabled             (0 << 2)
#define GPIO_PIN_CNF_PULL_PULLDOWN             (1 << 2)
#define GPIO_PIN_CNF_PULL_Pulldown             (1 << 2)
#define GPIO_PIN_CNF_PULL_PULLUP               (0x3 << 2)
#define GPIO_PIN_CNF_PULL_Pullup               (0x3 << 2)
/* Drive configuration */
/* Note: S stands for Standard. H stands for High drive. D stands for 
Disconnect. Eg. S0S1 is Standard '0', standard '1' */
#define DRIVE_S0S1                             (0)
#define DRIVE_H0S1                             (1)
#define DRIVE_S0H1                             (2)
#define DRIVE_H0H1                             (3)
#define DRIVE_D0S1                             (4)
#define DRIVE_D0H1                             (5)
#define DRIVE_S0D1                             (6)
#define DRIVE_D0D1                             (7)
#define GPIO_PIN_CNF_DRIVE(n)                  (((n)&0x07) << 8)
#define GPIO_PIN_CNF_DRIVE_S0S1                (0 << 8)
#define GPIO_PIN_CNF_DRIVE_H0S1                (1 << 8)
#define GPIO_PIN_CNF_DRIVE_S0H1                (0x2 << 8)
#define GPIO_PIN_CNF_DRIVE_H0H1                (0x3 << 8)
#define GPIO_PIN_CNF_DRIVE_D0S1                (0x4 << 8)
#define GPIO_PIN_CNF_DRIVE_D0H1                (0x5 << 8)
#define GPIO_PIN_CNF_DRIVE_S0D1                (0x6 << 8)
#define GPIO_PIN_CNF_DRIVE_H0D1                (0x7 << 8)
/* Pin sensing mechanism */
#define SENSE_DISABLED                         (0)
#define SENSE_HIGH                             (2)
#define SENSE_LOW                              (3)
#define GPIO_PIN_CNF_SENSE(n)                  (((n)&0x03) << 16)
#define GPIO_PIN_CNF_SENSE_DISABLED            (0 << 16)
#define GPIO_PIN_CNF_SENSE_Disabled            (0 << 16)
#define GPIO_PIN_CNF_SENSE_HIGH                (0x2 << 16)
#define GPIO_PIN_CNF_SENSE_High                (0x2 << 16)
#define GPIO_PIN_CNF_SENSE_LOW                 (0x3 << 16)
#define GPIO_PIN_CNF_SENSE_Low                 (0x3 << 16)

/* ------------------------------------------------------------------------- */
/* GPIO number definitions (for convenience) */
/** @defgroup gpio_pin_id GPIO Pin Identifiers
@ingroup gpio_defines

@{*/
#define GPIO(n)               (1 << n)
#define GPIO0                 (1 << 0)
#define GPIO1                 (1 << 1)
#define GPIO2                 (1 << 2)
#define GPIO3                 (1 << 3)
#define GPIO4                 (1 << 4)
#define GPIO5                 (1 << 5)
#define GPIO6                 (1 << 6)
#define GPIO7                 (1 << 7)
#define GPIO8                 (1 << 8)
#define GPIO9                 (1 << 9)
#define GPIO10                (1 << 10)
#define GPIO11                (1 << 11)
#define GPIO12                (1 << 12)
#define GPIO13                (1 << 13)
#define GPIO14                (1 << 14)
#define GPIO15                (1 << 15)
#define GPIO16                (1 << 16)
#define GPIO17                (1 << 17)
#define GPIO18                (1 << 18)
#define GPIO19                (1 << 19)
#define GPIO20                (1 << 20)
#define GPIO21                (1 << 21)
#define GPIO22                (1 << 22)
#define GPIO23                (1 << 23)
#define GPIO24                (1 << 24)
#define GPIO25                (1 << 25)
#define GPIO26                (1 << 26)
#define GPIO27                (1 << 27)
#define GPIO28                (1 << 28)
#define GPIO29                (1 << 29)
#define GPIO30                (1 << 30)
#define GPIO31                (1 << 31)
#define GPIO_ALL              0xffffffff
/*Pin number definitions for convenience*/
#define pin(n)            n
#define pin0              0
#define pin1              1
#define pin2              2
#define pin3              3
#define pin4              4
#define pin5              5
#define pin6              6
#define pin7              7
#define pin8              8 
#define pin9              9
#define pin10            10
#define pin11            11
#define pin12            12
#define pin13            13
#define pin14            14
#define pin15            15
#define pin16            16
#define pin17            17
#define pin18            18
#define pin19            19
#define pin20            20
#define pin21            21
#define pin22            22
#define pin23            23
#define pin24            24
#define pin25            25
#define pin26            26
#define pin27            27
#define pin28            28
#define pin29            29
#define pin30            30
#define pin31            31
/**@}*/

/* --- Function prototypes ------------------------------------------------- */

BEGIN_DECLS

void gpio_set(uint32_t gpios);
void gpio_clear(uint32_t gpios);
uint32_t gpio_read(uint32_t gpios);
void gpio_dir_output(uint32_t gpios);
void gpio_dir_input(uint32_t gpios);
void gpio_toggle(uint32_t gpios);
void gpio_config(uint32_t gpios, uint32_t dir, uint32_t input, 
			uint32_t pull, uint32_t drive, uint32_t sense);

END_DECLS
/**@}*/
#endif
/** @cond */
#else
#warning "gpio_common.h should not be included explicitly, only via gpio.h"
#endif
/** @endcond */

