/** @addtogroup uarte_defines PPI Defines
 *
 * @author @htmlonly &copy; @endhtmlonly 2018 
 * Gerrit Maus <funk@maus.xyz>, Luong Le <novercy@live.com>
 *
 */
/*
 * This file is part of the libopencm3 project.
 *
 * Copyright (C) 2018 Gerrit Maus <funk@maus.xyz>, Luong Le <novercy@live.com>
 *
 * This library is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library.  If not, see <http://www.gnu.org/licenses/>.
 */

/* THIS FILE SHOULD NOT BE INCLUDED DIRECTLY, BUT ONLY VIA PPI.H
The order of header inclusion is important. ppi.h includes the device
specific memorymap.h header before including this header file.*/

/** @cond */
#if defined(LIBOPENCM3_PPI_H)
/** @endcond */
#ifndef LIBOPENCM3_PPI_COMMON_H
#define LIBOPENCM3_PPI_COMMON_H

/**@{*/

/** @defgroup ppi_registers PPI Registers
 * @ingroup ppi_defines
 * @brief PPI Registers
@{*/
/* --------------------- PPI registers for NRF52 --------------------------- */

/* Tasks Registers */
struct PPI_TASKS_CHG_TYPE{
	uint32_t EN;
	uint32_t DIS;
};
#define PPI_TASKS_CHG    ((volatile struct PPI_TASKS_CHG_TYPE*)((PPI_BASE) + 0x000))
#define PPI_TASKS_CHG_EN(group)         MMIO32((PPI_BASE) + 0x000 + 8*group)
#define PPI_TASKS_CHG_DIS(group)        MMIO32((PPI_BASE) + 0x004 + 8*group)
#define PPI_TASKS_CHG0_EN               MMIO32((PPI_BASE) + 0x000)
#define PPI_TASKS_CHG0_DIS              MMIO32((PPI_BASE) + 0x004)
#define PPI_TASKS_CHG1_EN               MMIO32((PPI_BASE) + 0x008)
#define PPI_TASKS_CHG1_DIS              MMIO32((PPI_BASE) + 0x00C)
#define PPI_TASKS_CHG2_EN               MMIO32((PPI_BASE) + 0x010)
#define PPI_TASKS_CHG2_DIS              MMIO32((PPI_BASE) + 0x014)
#define PPI_TASKS_CHG3_EN               MMIO32((PPI_BASE) + 0x018)
#define PPI_TASKS_CHG3_DIS              MMIO32((PPI_BASE) + 0x01C)
#define PPI_TASKS_CHG4_EN               MMIO32((PPI_BASE) + 0x020)
#define PPI_TASKS_CHG4_DIS              MMIO32((PPI_BASE) + 0x024)
#define PPI_TASKS_CHG5_EN               MMIO32((PPI_BASE) + 0x028)
#define PPI_TASKS_CHG5_DIS              MMIO32((PPI_BASE) + 0x02C)

/* Registers */
#define PPI_CHEN                        MMIO32((PPI_BASE) + 0x500)
#define PPI_CHENSET                     MMIO32((PPI_BASE) + 0x504)
#define PPI_CHENCLR                     MMIO32((PPI_BASE) + 0x508)

struct PPI_CH_TYPE{
	uint32_t EEP;
	uint32_t TEP;
};
#define PPI_CH            ((volatile struct PPI_CH_TYPE*)((PPI_BASE) + 0x510))
#define PPI_CH_EEP(channel)             MMIO32((PPI_BASE) + 0x510 + 8*channel)
#define PPI_CH_TEP(channel)             MMIO32((PPI_BASE) + 0x514 + 8*channel)
#define PPI_CH0_EEP                     MMIO32((PPI_BASE) + 0x510)
#define PPI_CH0_TEP                     MMIO32((PPI_BASE) + 0x514)
#define PPI_CH1_EEP                     MMIO32((PPI_BASE) + 0x518)
#define PPI_CH1_TEP                     MMIO32((PPI_BASE) + 0x51C)
#define PPI_CH2_EEP                     MMIO32((PPI_BASE) + 0x520)
#define PPI_CH2_TEP                     MMIO32((PPI_BASE) + 0x524)
#define PPI_CH3_EEP                     MMIO32((PPI_BASE) + 0x528)
#define PPI_CH3_TEP                     MMIO32((PPI_BASE) + 0x52C)
#define PPI_CH4_EEP                     MMIO32((PPI_BASE) + 0x530)
#define PPI_CH4_TEP                     MMIO32((PPI_BASE) + 0x534)
#define PPI_CH5_EEP                     MMIO32((PPI_BASE) + 0x538)
#define PPI_CH5_TEP                     MMIO32((PPI_BASE) + 0x53C)
#define PPI_CH6_EEP                     MMIO32((PPI_BASE) + 0x540)
#define PPI_CH6_TEP                     MMIO32((PPI_BASE) + 0x544)
#define PPI_CH7_EEP                     MMIO32((PPI_BASE) + 0x548)
#define PPI_CH7_TEP                     MMIO32((PPI_BASE) + 0x54C)
#define PPI_CH8_EEP                     MMIO32((PPI_BASE) + 0x550)
#define PPI_CH8_TEP                     MMIO32((PPI_BASE) + 0x554)
#define PPI_CH9_EEP                     MMIO32((PPI_BASE) + 0x558)
#define PPI_CH9_TEP                     MMIO32((PPI_BASE) + 0x55C)
#define PPI_CH10_EEP                    MMIO32((PPI_BASE) + 0x560)
#define PPI_CH10_TEP                    MMIO32((PPI_BASE) + 0x564)
#define PPI_CH11_EEP                    MMIO32((PPI_BASE) + 0x568)
#define PPI_CH11_TEP                    MMIO32((PPI_BASE) + 0x56C)
#define PPI_CH12_EEP                    MMIO32((PPI_BASE) + 0x570)
#define PPI_CH12_TEP                    MMIO32((PPI_BASE) + 0x574)
#define PPI_CH13_EEP                    MMIO32((PPI_BASE) + 0x578)
#define PPI_CH13_TEP                    MMIO32((PPI_BASE) + 0x57C)
#define PPI_CH14_EEP                    MMIO32((PPI_BASE) + 0x580)
#define PPI_CH14_TEP                    MMIO32((PPI_BASE) + 0x584)
#define PPI_CH15_EEP                    MMIO32((PPI_BASE) + 0x588)
#define PPI_CH15_TEP                    MMIO32((PPI_BASE) + 0x58C)
#define PPI_CH16_EEP                    MMIO32((PPI_BASE) + 0x590)
#define PPI_CH16_TEP                    MMIO32((PPI_BASE) + 0x594)
#define PPI_CH17_EEP                    MMIO32((PPI_BASE) + 0x598)
#define PPI_CH17_TEP                    MMIO32((PPI_BASE) + 0x59C)
#define PPI_CH18_EEP                    MMIO32((PPI_BASE) + 0x5A0)
#define PPI_CH18_TEP                    MMIO32((PPI_BASE) + 0x5A4)
#define PPI_CH19_EEP                    MMIO32((PPI_BASE) + 0x5A8)
#define PPI_CH19_TEP                    MMIO32((PPI_BASE) + 0x5AC)

#define PPI_CHG                         PTRIO32((PPI_BASE) + 0x800)
#define PPI_CHG0                        MMIO32((PPI_BASE) + 0x800)
#define PPI_CHG1                        MMIO32((PPI_BASE) + 0x804)
#define PPI_CHG2                        MMIO32((PPI_BASE) + 0x808)
#define PPI_CHG3                        MMIO32((PPI_BASE) + 0x80C)
#define PPI_CHG4                        MMIO32((PPI_BASE) + 0x810)
#define PPI_CHG5                        MMIO32((PPI_BASE) + 0x814)

struct PPI_FORK_TYPE{
	uint32_t TEP;
};
#define PPI_FORK      ((volatile struct PPI_FORK_TYPE*)((PPI_BASE) + 0x910))
#define PPI_FORK_TEP                    PTRIO32((PPI_BASE) + 0x910)
#define PPI_FORK0_TEP                   MMIO32((PPI_BASE) + 0x910)
#define PPI_FORK1_TEP                   MMIO32((PPI_BASE) + 0x914)
#define PPI_FORK2_TEP                   MMIO32((PPI_BASE) + 0x918)
#define PPI_FORK3_TEP                   MMIO32((PPI_BASE) + 0x91C)
#define PPI_FORK4_TEP                   MMIO32((PPI_BASE) + 0x920)
#define PPI_FORK5_TEP                   MMIO32((PPI_BASE) + 0x924)
#define PPI_FORK6_TEP                   MMIO32((PPI_BASE) + 0x928)
#define PPI_FORK7_TEP                   MMIO32((PPI_BASE) + 0x92C)
#define PPI_FORK8_TEP                   MMIO32((PPI_BASE) + 0x930)
#define PPI_FORK9_TEP                   MMIO32((PPI_BASE) + 0x934)
#define PPI_FORK10_TEP                  MMIO32((PPI_BASE) + 0x938)
#define PPI_FORK11_TEP                  MMIO32((PPI_BASE) + 0x93C)
#define PPI_FORK12_TEP                  MMIO32((PPI_BASE) + 0x940)
#define PPI_FORK13_TEP                  MMIO32((PPI_BASE) + 0x944)
#define PPI_FORK14_TEP                  MMIO32((PPI_BASE) + 0x948)
#define PPI_FORK15_TEP                  MMIO32((PPI_BASE) + 0x94C)
#define PPI_FORK16_TEP                  MMIO32((PPI_BASE) + 0x950)
#define PPI_FORK17_TEP                  MMIO32((PPI_BASE) + 0x954)
#define PPI_FORK18_TEP                  MMIO32((PPI_BASE) + 0x958)
#define PPI_FORK19_TEP                  MMIO32((PPI_BASE) + 0x95C)
#define PPI_FORK20_TEP                  MMIO32((PPI_BASE) + 0x960)
#define PPI_FORK21_TEP                  MMIO32((PPI_BASE) + 0x964)
#define PPI_FORK22_TEP                  MMIO32((PPI_BASE) + 0x968)
#define PPI_FORK23_TEP                  MMIO32((PPI_BASE) + 0x96C)
#define PPI_FORK24_TEP                  MMIO32((PPI_BASE) + 0x970)
#define PPI_FORK25_TEP                  MMIO32((PPI_BASE) + 0x974)
#define PPI_FORK26_TEP                  MMIO32((PPI_BASE) + 0x978)
#define PPI_FORK27_TEP                  MMIO32((PPI_BASE) + 0x97C)
#define PPI_FORK28_TEP                  MMIO32((PPI_BASE) + 0x980)
#define PPI_FORK29_TEP                  MMIO32((PPI_BASE) + 0x984)
#define PPI_FORK30_TEP                  MMIO32((PPI_BASE) + 0x988)
#define PPI_FORK31_TEP                  MMIO32((PPI_BASE) + 0x98C)
/**@}*/

/* --- PPI_CHEN values ----------------------------------------------------- */
/** @defgroup ppi_chen Enable or disable Channel
@ingroup ppi_defines
@{*/
#define PPI_CHEN_CH_DISABLED(channel)                (0 << channel)
#define PPI_CHEN_CH_Disabled(channel)                (0 << channel)
#define PPI_CHEN_CH_ENABLED(channel)                 (1 << channel)
#define PPI_CHEN_CH_Enabled(channel)                 (1 << channel)
#define PPI_CHEN_CH0_DISABLED                        (0 << 0)
#define PPI_CHEN_CH0_Disabled                        (0 << 0)
#define PPI_CHEN_CH0_ENABLED                         (1 << 0)
#define PPI_CHEN_CH0_Enabled                         (1 << 0)
#define PPI_CHEN_CH1_DISABLED                        (0 << 1)
#define PPI_CHEN_CH1_Disabled                        (0 << 1)
#define PPI_CHEN_CH1_ENABLED                         (1 << 1)
#define PPI_CHEN_CH1_Enabled                         (1 << 1)
#define PPI_CHEN_CH2_DISABLED                        (0 << 2)
#define PPI_CHEN_CH2_Disabled                        (0 << 2)
#define PPI_CHEN_CH2_ENABLED                         (1 << 2)
#define PPI_CHEN_CH2_Enabled                         (1 << 2)
#define PPI_CHEN_CH3_DISABLED                        (0 << 3)
#define PPI_CHEN_CH3_Disabled                        (0 << 3)
#define PPI_CHEN_CH3_ENABLED                         (1 << 3)
#define PPI_CHEN_CH3_Enabled                         (1 << 3)
#define PPI_CHEN_CH4_DISABLED                        (0 << 4)
#define PPI_CHEN_CH4_Disabled                        (0 << 4)
#define PPI_CHEN_CH4_ENABLED                         (1 << 4)
#define PPI_CHEN_CH4_Enabled                         (1 << 4)
#define PPI_CHEN_CH5_DISABLED                        (0 << 5)
#define PPI_CHEN_CH5_Disabled                        (0 << 5)
#define PPI_CHEN_CH5_ENABLED                         (1 << 5)
#define PPI_CHEN_CH5_Enabled                         (1 << 5)
#define PPI_CHEN_CH6_DISABLED                        (0 << 6)
#define PPI_CHEN_CH6_Disabled                        (0 << 6)
#define PPI_CHEN_CH6_ENABLED                         (1 << 6)
#define PPI_CHEN_CH6_Enabled                         (1 << 6)
#define PPI_CHEN_CH7_DISABLED                        (0 << 7)
#define PPI_CHEN_CH7_Disabled                        (0 << 7)
#define PPI_CHEN_CH7_ENABLED                         (1 << 7)
#define PPI_CHEN_CH7_Enabled                         (1 << 7)
#define PPI_CHEN_CH8_DISABLED                        (0 << 8)
#define PPI_CHEN_CH8_Disabled                        (0 << 8)
#define PPI_CHEN_CH8_ENABLED                         (1 << 8)
#define PPI_CHEN_CH8_Enabled                         (1 << 8)
#define PPI_CHEN_CH9_DISABLED                        (0 << 9)
#define PPI_CHEN_CH9_Disabled                        (0 << 9)
#define PPI_CHEN_CH9_ENABLED                         (1 << 9)
#define PPI_CHEN_CH9_Enabled                         (1 << 9)
#define PPI_CHEN_CH10_DISABLED                       (0 << 10)
#define PPI_CHEN_CH10_Disabled                       (0 << 10)
#define PPI_CHEN_CH10_ENABLED                        (1 << 10)
#define PPI_CHEN_CH10_Enabled                        (1 << 10)
#define PPI_CHEN_CH11_DISABLED                       (0 << 11)
#define PPI_CHEN_CH11_Disabled                       (0 << 11)
#define PPI_CHEN_CH11_ENABLED                        (1 << 11)
#define PPI_CHEN_CH11_Enabled                        (1 << 11)
#define PPI_CHEN_CH12_DISABLED                       (0 << 12)
#define PPI_CHEN_CH12_Disabled                       (0 << 12)
#define PPI_CHEN_CH12_ENABLED                        (1 << 12)
#define PPI_CHEN_CH12_Enabled                        (1 << 12)
#define PPI_CHEN_CH13_DISABLED                       (0 << 13)
#define PPI_CHEN_CH13_Disabled                       (0 << 13)
#define PPI_CHEN_CH13_ENABLED                        (1 << 13)
#define PPI_CHEN_CH13_Enabled                        (1 << 13)
#define PPI_CHEN_CH14_DISABLED                       (0 << 14)
#define PPI_CHEN_CH14_Disabled                       (0 << 14)
#define PPI_CHEN_CH14_ENABLED                        (1 << 14)
#define PPI_CHEN_CH14_Enabled                        (1 << 14)
#define PPI_CHEN_CH15_DISABLED                       (0 << 15)
#define PPI_CHEN_CH15_Disabled                       (0 << 15)
#define PPI_CHEN_CH15_ENABLED                        (1 << 15)
#define PPI_CHEN_CH15_Enabled                        (1 << 15)
#define PPI_CHEN_CH16_DISABLED                       (0 << 16)
#define PPI_CHEN_CH16_Disabled                       (0 << 16)
#define PPI_CHEN_CH16_ENABLED                        (1 << 16)
#define PPI_CHEN_CH16_Enabled                        (1 << 16)
#define PPI_CHEN_CH17_DISABLED                       (0 << 17)
#define PPI_CHEN_CH17_Disabled                       (0 << 17)
#define PPI_CHEN_CH17_ENABLED                        (1 << 17)
#define PPI_CHEN_CH17_Enabled                        (1 << 17)
#define PPI_CHEN_CH18_DISABLED                       (0 << 18)
#define PPI_CHEN_CH18_Disabled                       (0 << 18)
#define PPI_CHEN_CH18_ENABLED                        (1 << 18)
#define PPI_CHEN_CH18_Enabled                        (1 << 18)
#define PPI_CHEN_CH19_DISABLED                       (0 << 19)
#define PPI_CHEN_CH19_Disabled                       (0 << 19)
#define PPI_CHEN_CH19_ENABLED                        (1 << 19)
#define PPI_CHEN_CH19_Enabled                        (1 << 19)
#define PPI_CHEN_CH20_DISABLED                       (0 << 20)
#define PPI_CHEN_CH20_Disabled                       (0 << 20)
#define PPI_CHEN_CH20_ENABLED                        (1 << 20)
#define PPI_CHEN_CH20_Enabled                        (1 << 20)
#define PPI_CHEN_CH21_DISABLED                       (0 << 21)
#define PPI_CHEN_CH21_Disabled                       (0 << 21)
#define PPI_CHEN_CH21_ENABLED                        (1 << 21)
#define PPI_CHEN_CH21_Enabled                        (1 << 21)
#define PPI_CHEN_CH22_DISABLED                       (0 << 22)
#define PPI_CHEN_CH22_Disabled                       (0 << 22)
#define PPI_CHEN_CH22_ENABLED                        (1 << 22)
#define PPI_CHEN_CH22_Enabled                        (1 << 22)
#define PPI_CHEN_CH23_DISABLED                       (0 << 23)
#define PPI_CHEN_CH23_Disabled                       (0 << 23)
#define PPI_CHEN_CH23_ENABLED                        (1 << 23)
#define PPI_CHEN_CH23_Enabled                        (1 << 23)
#define PPI_CHEN_CH24_DISABLED                       (0 << 24)
#define PPI_CHEN_CH24_Disabled                       (0 << 24)
#define PPI_CHEN_CH24_ENABLED                        (1 << 24)
#define PPI_CHEN_CH24_Enabled                        (1 << 24)
#define PPI_CHEN_CH25_DISABLED                       (0 << 25)
#define PPI_CHEN_CH25_Disabled                       (0 << 25)
#define PPI_CHEN_CH25_ENABLED                        (1 << 25)
#define PPI_CHEN_CH25_Enabled                        (1 << 25)
#define PPI_CHEN_CH26_DISABLED                       (0 << 26)
#define PPI_CHEN_CH26_Disabled                       (0 << 26)
#define PPI_CHEN_CH26_ENABLED                        (1 << 26)
#define PPI_CHEN_CH26_Enabled                        (1 << 26)
#define PPI_CHEN_CH27_DISABLED                       (0 << 27)
#define PPI_CHEN_CH27_Disabled                       (0 << 27)
#define PPI_CHEN_CH27_ENABLED                        (1 << 27)
#define PPI_CHEN_CH27_Enabled                        (1 << 27)
#define PPI_CHEN_CH28_DISABLED                       (0 << 28)
#define PPI_CHEN_CH28_Disabled                       (0 << 28)
#define PPI_CHEN_CH28_ENABLED                        (1 << 28)
#define PPI_CHEN_CH28_Enabled                        (1 << 28)
#define PPI_CHEN_CH29_DISABLED                       (0 << 29)
#define PPI_CHEN_CH29_Disabled                       (0 << 29)
#define PPI_CHEN_CH29_ENABLED                        (1 << 29)
#define PPI_CHEN_CH29_Enabled                        (1 << 29)
#define PPI_CHEN_CH30_DISABLED                       (0 << 30)
#define PPI_CHEN_CH30_Disabled                       (0 << 30)
#define PPI_CHEN_CH30_ENABLED                        (1 << 30)
#define PPI_CHEN_CH30_Enabled                        (1 << 30)
#define PPI_CHEN_CH31_DISABLED                       (0 << 31)
#define PPI_CHEN_CH31_Disabled                       (0 << 31)
#define PPI_CHEN_CH31_ENABLED                        (1 << 31)
#define PPI_CHEN_CH31_Enabled                        (1 << 31)
/**@}*/

/* --- PPI_CHENSET values -------------------------------------------------- */
/** @defgroup ppi_chenset Enable Channel set register
@ingroup ppi_defines
@{*/
#define PPI_CHENSET_CH_SET(channel)                     (1 << channel)
#define PPI_CHENSET_CH_Set(channel)                     (1 << channel)
#define PPI_CHENSET_CH_ENABLED(channel)                 (1 << channel)
#define PPI_CHENSET_CH_Enabled(channel)                 (1 << channel)
#define PPI_CHENSET_CH0_SET                             (1 << 0)
#define PPI_CHENSET_CH0_Set                             (1 << 0)
#define PPI_CHENSET_CH0_ENABLED                         (1 << 0)
#define PPI_CHENSET_CH0_Enabled                         (1 << 0)
#define PPI_CHENSET_CH1_SET                             (1 << 1)
#define PPI_CHENSET_CH1_Set                             (1 << 1)
#define PPI_CHENSET_CH1_ENABLED                         (1 << 1)
#define PPI_CHENSET_CH1_Enabled                         (1 << 1)
#define PPI_CHENSET_CH2_SET                             (1 << 2)
#define PPI_CHENSET_CH2_Set                             (1 << 2)
#define PPI_CHENSET_CH2_ENABLED                         (1 << 2)
#define PPI_CHENSET_CH2_Enabled                         (1 << 2)
#define PPI_CHENSET_CH3_SET                             (1 << 3)
#define PPI_CHENSET_CH3_Set                             (1 << 3)
#define PPI_CHENSET_CH3_ENABLED                         (1 << 3)
#define PPI_CHENSET_CH3_Enabled                         (1 << 3)
#define PPI_CHENSET_CH4_SET                             (1 << 4)
#define PPI_CHENSET_CH4_Set                             (1 << 4)
#define PPI_CHENSET_CH4_ENABLED                         (1 << 4)
#define PPI_CHENSET_CH4_Enabled                         (1 << 4)
#define PPI_CHENSET_CH5_SET                             (1 << 5)
#define PPI_CHENSET_CH5_Set                             (1 << 5)
#define PPI_CHENSET_CH5_ENABLED                         (1 << 5)
#define PPI_CHENSET_CH5_Enabled                         (1 << 5)
#define PPI_CHENSET_CH6_SET                             (1 << 6)
#define PPI_CHENSET_CH6_Set                             (1 << 6)
#define PPI_CHENSET_CH6_ENABLED                         (1 << 6)
#define PPI_CHENSET_CH6_Enabled                         (1 << 6)
#define PPI_CHENSET_CH7_SET                             (1 << 7)
#define PPI_CHENSET_CH7_Set                             (1 << 7)
#define PPI_CHENSET_CH7_ENABLED                         (1 << 7)
#define PPI_CHENSET_CH7_Enabled                         (1 << 7)
#define PPI_CHENSET_CH8_SET                             (1 << 8)
#define PPI_CHENSET_CH8_Set                             (1 << 8)
#define PPI_CHENSET_CH8_ENABLED                         (1 << 8)
#define PPI_CHENSET_CH8_Enabled                         (1 << 8)
#define PPI_CHENSET_CH9_SET                             (1 << 9)
#define PPI_CHENSET_CH9_Set                             (1 << 9)
#define PPI_CHENSET_CH9_ENABLED                         (1 << 9)
#define PPI_CHENSET_CH9_Enabled                         (1 << 9)
#define PPI_CHENSET_CH10_SET                            (1 << 10)
#define PPI_CHENSET_CH10_Set                            (1 << 10)
#define PPI_CHENSET_CH10_ENABLED                        (1 << 10)
#define PPI_CHENSET_CH10_Enabled                        (1 << 10)
#define PPI_CHENSET_CH11_SET                            (1 << 11)
#define PPI_CHENSET_CH11_Set                            (1 << 11)
#define PPI_CHENSET_CH11_ENABLED                        (1 << 11)
#define PPI_CHENSET_CH11_Enabled                        (1 << 11)
#define PPI_CHENSET_CH12_SET                            (1 << 12)
#define PPI_CHENSET_CH12_Set                            (1 << 12)
#define PPI_CHENSET_CH12_ENABLED                        (1 << 12)
#define PPI_CHENSET_CH12_Enabled                        (1 << 12)
#define PPI_CHENSET_CH13_SET                            (1 << 13)
#define PPI_CHENSET_CH13_Set                            (1 << 13)
#define PPI_CHENSET_CH13_ENABLED                        (1 << 13)
#define PPI_CHENSET_CH13_Enabled                        (1 << 13)
#define PPI_CHENSET_CH14_SET                            (1 << 14)
#define PPI_CHENSET_CH14_Set                            (1 << 14)
#define PPI_CHENSET_CH14_ENABLED                        (1 << 14)
#define PPI_CHENSET_CH14_Enabled                        (1 << 14)
#define PPI_CHENSET_CH15_SET                            (1 << 15)
#define PPI_CHENSET_CH15_Set                            (1 << 15)
#define PPI_CHENSET_CH15_ENABLED                        (1 << 15)
#define PPI_CHENSET_CH15_Enabled                        (1 << 15)
#define PPI_CHENSET_CH16_SET                            (1 << 16)
#define PPI_CHENSET_CH16_Set                            (1 << 16)
#define PPI_CHENSET_CH16_ENABLED                        (1 << 16)
#define PPI_CHENSET_CH16_Enabled                        (1 << 16)
#define PPI_CHENSET_CH17_SET                            (1 << 17)
#define PPI_CHENSET_CH17_Set                            (1 << 17)
#define PPI_CHENSET_CH17_ENABLED                        (1 << 17)
#define PPI_CHENSET_CH17_Enabled                        (1 << 17)
#define PPI_CHENSET_CH18_SET                            (1 << 18)
#define PPI_CHENSET_CH18_Set                            (1 << 18)
#define PPI_CHENSET_CH18_ENABLED                        (1 << 18)
#define PPI_CHENSET_CH18_Enabled                        (1 << 18)
#define PPI_CHENSET_CH19_SET                            (1 << 19)
#define PPI_CHENSET_CH19_Set                            (1 << 19)
#define PPI_CHENSET_CH19_ENABLED                        (1 << 19)
#define PPI_CHENSET_CH19_Enabled                        (1 << 19)
#define PPI_CHENSET_CH20_SET                            (1 << 20)
#define PPI_CHENSET_CH20_Set                            (1 << 20)
#define PPI_CHENSET_CH20_ENABLED                        (1 << 20)
#define PPI_CHENSET_CH20_Enabled                        (1 << 20)
#define PPI_CHENSET_CH21_SET                            (1 << 21)
#define PPI_CHENSET_CH21_Set                            (1 << 21)
#define PPI_CHENSET_CH21_ENABLED                        (1 << 21)
#define PPI_CHENSET_CH21_Enabled                        (1 << 21)
#define PPI_CHENSET_CH22_SET                            (1 << 22)
#define PPI_CHENSET_CH22_Set                            (1 << 22)
#define PPI_CHENSET_CH22_ENABLED                        (1 << 22)
#define PPI_CHENSET_CH22_Enabled                        (1 << 22)
#define PPI_CHENSET_CH23_SET                            (1 << 23)
#define PPI_CHENSET_CH23_Set                            (1 << 23)
#define PPI_CHENSET_CH23_ENABLED                        (1 << 23)
#define PPI_CHENSET_CH23_Enabled                        (1 << 23)
#define PPI_CHENSET_CH24_SET                            (1 << 24)
#define PPI_CHENSET_CH24_Set                            (1 << 24)
#define PPI_CHENSET_CH24_ENABLED                        (1 << 24)
#define PPI_CHENSET_CH24_Enabled                        (1 << 24)
#define PPI_CHENSET_CH25_SET                            (1 << 25)
#define PPI_CHENSET_CH25_Set                            (1 << 25)
#define PPI_CHENSET_CH25_ENABLED                        (1 << 25)
#define PPI_CHENSET_CH25_Enabled                        (1 << 25)
#define PPI_CHENSET_CH26_SET                            (1 << 26)
#define PPI_CHENSET_CH26_Set                            (1 << 26)
#define PPI_CHENSET_CH26_ENABLED                        (1 << 26)
#define PPI_CHENSET_CH26_Enabled                        (1 << 26)
#define PPI_CHENSET_CH27_SET                            (1 << 27)
#define PPI_CHENSET_CH27_Set                            (1 << 27)
#define PPI_CHENSET_CH27_ENABLED                        (1 << 27)
#define PPI_CHENSET_CH27_Enabled                        (1 << 27)
#define PPI_CHENSET_CH28_SET                            (1 << 28)
#define PPI_CHENSET_CH28_Set                            (1 << 28)
#define PPI_CHENSET_CH28_ENABLED                        (1 << 28)
#define PPI_CHENSET_CH28_Enabled                        (1 << 28)
#define PPI_CHENSET_CH29_SET                            (1 << 29)
#define PPI_CHENSET_CH29_Set                            (1 << 29)
#define PPI_CHENSET_CH29_ENABLED                        (1 << 29)
#define PPI_CHENSET_CH29_Enabled                        (1 << 29)
#define PPI_CHENSET_CH30_SET                            (1 << 30)
#define PPI_CHENSET_CH30_Set                            (1 << 30)
#define PPI_CHENSET_CH30_ENABLED                        (1 << 30)
#define PPI_CHENSET_CH30_Enabled                        (1 << 30)
#define PPI_CHENSET_CH31_SET                            (1 << 31)
#define PPI_CHENSET_CH31_Set                            (1 << 31)
#define PPI_CHENSET_CH31_ENABLED                        (1 << 31)
#define PPI_CHENSET_CH31_Enabled                        (1 << 31)
/**@}*/

/* --- PPI_CHENCLR values -------------------------------------------------- */
/** @defgroup ppi_chenclr Enable Channel clear register
@ingroup ppi_defines
@{*/
#define PPI_CHENCLR_CH_CLEAR(channel)                   (1 << channel)
#define PPI_CHENCLR_CH_Clear(channel)                   (1 << channel)
#define PPI_CHENCLR_CH_ENABLED(channel)                 (1 << channel)
#define PPI_CHENCLR_CH_Enabled(channel)                 (1 << channel)
#define PPI_CHENCLR_CH0_CLEAR                           (1 << 0)
#define PPI_CHENCLR_CH0_Clear                           (1 << 0)
#define PPI_CHENCLR_CH0_ENABLED                         (1 << 0)
#define PPI_CHENCLR_CH0_Enabled                         (1 << 0)
#define PPI_CHENCLR_CH1_CLEAR                           (1 << 1)
#define PPI_CHENCLR_CH1_Clear                           (1 << 1)
#define PPI_CHENCLR_CH1_ENABLED                         (1 << 1)
#define PPI_CHENCLR_CH1_Enabled                         (1 << 1)
#define PPI_CHENCLR_CH2_CLEAR                           (1 << 2)
#define PPI_CHENCLR_CH2_Clear                           (1 << 2)
#define PPI_CHENCLR_CH2_ENABLED                         (1 << 2)
#define PPI_CHENCLR_CH2_Enabled                         (1 << 2)
#define PPI_CHENCLR_CH3_CLEAR                           (1 << 3)
#define PPI_CHENCLR_CH3_Clear                           (1 << 3)
#define PPI_CHENCLR_CH3_ENABLED                         (1 << 3)
#define PPI_CHENCLR_CH3_Enabled                         (1 << 3)
#define PPI_CHENCLR_CH4_CLEAR                           (1 << 4)
#define PPI_CHENCLR_CH4_Clear                           (1 << 4)
#define PPI_CHENCLR_CH4_ENABLED                         (1 << 4)
#define PPI_CHENCLR_CH4_Enabled                         (1 << 4)
#define PPI_CHENCLR_CH5_CLEAR                           (1 << 5)
#define PPI_CHENCLR_CH5_Clear                           (1 << 5)
#define PPI_CHENCLR_CH5_ENABLED                         (1 << 5)
#define PPI_CHENCLR_CH5_Enabled                         (1 << 5)
#define PPI_CHENCLR_CH6_CLEAR                           (1 << 6)
#define PPI_CHENCLR_CH6_Clear                           (1 << 6)
#define PPI_CHENCLR_CH6_ENABLED                         (1 << 6)
#define PPI_CHENCLR_CH6_Enabled                         (1 << 6)
#define PPI_CHENCLR_CH7_CLEAR                           (1 << 7)
#define PPI_CHENCLR_CH7_Clear                           (1 << 7)
#define PPI_CHENCLR_CH7_ENABLED                         (1 << 7)
#define PPI_CHENCLR_CH7_Enabled                         (1 << 7)
#define PPI_CHENCLR_CH8_CLEAR                           (1 << 8)
#define PPI_CHENCLR_CH8_Clear                           (1 << 8)
#define PPI_CHENCLR_CH8_ENABLED                         (1 << 8)
#define PPI_CHENCLR_CH8_Enabled                         (1 << 8)
#define PPI_CHENCLR_CH9_CLEAR                           (1 << 9)
#define PPI_CHENCLR_CH9_Clear                           (1 << 9)
#define PPI_CHENCLR_CH9_ENABLED                         (1 << 9)
#define PPI_CHENCLR_CH9_Enabled                         (1 << 9)
#define PPI_CHENCLR_CH10_CLEAR                          (1 << 10)
#define PPI_CHENCLR_CH10_Clear                          (1 << 10)
#define PPI_CHENCLR_CH10_ENABLED                        (1 << 10)
#define PPI_CHENCLR_CH10_Enabled                        (1 << 10)
#define PPI_CHENCLR_CH11_CLEAR                          (1 << 11)
#define PPI_CHENCLR_CH11_Clear                          (1 << 11)
#define PPI_CHENCLR_CH11_ENABLED                        (1 << 11)
#define PPI_CHENCLR_CH11_Enabled                        (1 << 11)
#define PPI_CHENCLR_CH12_CLEAR                          (1 << 12)
#define PPI_CHENCLR_CH12_Clear                          (1 << 12)
#define PPI_CHENCLR_CH12_ENABLED                        (1 << 12)
#define PPI_CHENCLR_CH12_Enabled                        (1 << 12)
#define PPI_CHENCLR_CH13_CLEAR                          (1 << 13)
#define PPI_CHENCLR_CH13_Clear                          (1 << 13)
#define PPI_CHENCLR_CH13_ENABLED                        (1 << 13)
#define PPI_CHENCLR_CH13_Enabled                        (1 << 13)
#define PPI_CHENCLR_CH14_CLEAR                          (1 << 14)
#define PPI_CHENCLR_CH14_Clear                          (1 << 14)
#define PPI_CHENCLR_CH14_ENABLED                        (1 << 14)
#define PPI_CHENCLR_CH14_Enabled                        (1 << 14)
#define PPI_CHENCLR_CH15_CLEAR                          (1 << 15)
#define PPI_CHENCLR_CH15_Clear                          (1 << 15)
#define PPI_CHENCLR_CH15_ENABLED                        (1 << 15)
#define PPI_CHENCLR_CH15_Enabled                        (1 << 15)
#define PPI_CHENCLR_CH16_CLEAR                          (1 << 16)
#define PPI_CHENCLR_CH16_Clear                          (1 << 16)
#define PPI_CHENCLR_CH16_ENABLED                        (1 << 16)
#define PPI_CHENCLR_CH16_Enabled                        (1 << 16)
#define PPI_CHENCLR_CH17_CLEAR                          (1 << 17)
#define PPI_CHENCLR_CH17_Clear                          (1 << 17)
#define PPI_CHENCLR_CH17_ENABLED                        (1 << 17)
#define PPI_CHENCLR_CH17_Enabled                        (1 << 17)
#define PPI_CHENCLR_CH18_CLEAR                          (1 << 18)
#define PPI_CHENCLR_CH18_Clear                          (1 << 18)
#define PPI_CHENCLR_CH18_ENABLED                        (1 << 18)
#define PPI_CHENCLR_CH18_Enabled                        (1 << 18)
#define PPI_CHENCLR_CH19_CLEAR                          (1 << 19)
#define PPI_CHENCLR_CH19_Clear                          (1 << 19)
#define PPI_CHENCLR_CH19_ENABLED                        (1 << 19)
#define PPI_CHENCLR_CH19_Enabled                        (1 << 19)
#define PPI_CHENCLR_CH20_CLEAR                          (1 << 20)
#define PPI_CHENCLR_CH20_Clear                          (1 << 20)
#define PPI_CHENCLR_CH20_ENABLED                        (1 << 20)
#define PPI_CHENCLR_CH20_Enabled                        (1 << 20)
#define PPI_CHENCLR_CH21_CLEAR                          (1 << 21)
#define PPI_CHENCLR_CH21_Clear                          (1 << 21)
#define PPI_CHENCLR_CH21_ENABLED                        (1 << 21)
#define PPI_CHENCLR_CH21_Enabled                        (1 << 21)
#define PPI_CHENCLR_CH22_CLEAR                          (1 << 22)
#define PPI_CHENCLR_CH22_Clear                          (1 << 22)
#define PPI_CHENCLR_CH22_ENABLED                        (1 << 22)
#define PPI_CHENCLR_CH22_Enabled                        (1 << 22)
#define PPI_CHENCLR_CH23_CLEAR                          (1 << 23)
#define PPI_CHENCLR_CH23_Clear                          (1 << 23)
#define PPI_CHENCLR_CH23_ENABLED                        (1 << 23)
#define PPI_CHENCLR_CH23_Enabled                        (1 << 23)
#define PPI_CHENCLR_CH24_CLEAR                          (1 << 24)
#define PPI_CHENCLR_CH24_Clear                          (1 << 24)
#define PPI_CHENCLR_CH24_ENABLED                        (1 << 24)
#define PPI_CHENCLR_CH24_Enabled                        (1 << 24)
#define PPI_CHENCLR_CH25_CLEAR                          (1 << 25)
#define PPI_CHENCLR_CH25_Clear                          (1 << 25)
#define PPI_CHENCLR_CH25_ENABLED                        (1 << 25)
#define PPI_CHENCLR_CH25_Enabled                        (1 << 25)
#define PPI_CHENCLR_CH26_CLEAR                          (1 << 26)
#define PPI_CHENCLR_CH26_Clear                          (1 << 26)
#define PPI_CHENCLR_CH26_ENABLED                        (1 << 26)
#define PPI_CHENCLR_CH26_Enabled                        (1 << 26)
#define PPI_CHENCLR_CH27_CLEAR                          (1 << 27)
#define PPI_CHENCLR_CH27_Clear                          (1 << 27)
#define PPI_CHENCLR_CH27_ENABLED                        (1 << 27)
#define PPI_CHENCLR_CH27_Enabled                        (1 << 27)
#define PPI_CHENCLR_CH28_CLEAR                          (1 << 28)
#define PPI_CHENCLR_CH28_Clear                          (1 << 28)
#define PPI_CHENCLR_CH28_ENABLED                        (1 << 28)
#define PPI_CHENCLR_CH28_Enabled                        (1 << 28)
#define PPI_CHENCLR_CH29_CLEAR                          (1 << 29)
#define PPI_CHENCLR_CH29_Clear                          (1 << 29)
#define PPI_CHENCLR_CH29_ENABLED                        (1 << 29)
#define PPI_CHENCLR_CH29_Enabled                        (1 << 29)
#define PPI_CHENCLR_CH30_CLEAR                          (1 << 30)
#define PPI_CHENCLR_CH30_Clear                          (1 << 30)
#define PPI_CHENCLR_CH30_ENABLED                        (1 << 30)
#define PPI_CHENCLR_CH30_Enabled                        (1 << 30)
#define PPI_CHENCLR_CH31_CLEAR                          (1 << 31)
#define PPI_CHENCLR_CH31_Clear                          (1 << 31)
#define PPI_CHENCLR_CH31_ENABLED                        (1 << 31)
#define PPI_CHENCLR_CH31_Enabled                        (1 << 31)
/**@}*/

/* --- PPI_CHG values ------------------------------------------------------ */
/** @defgroup ppi_chg Include or exclude Channel
@ingroup ppi_defines
@{*/
#define PPI_CHG_CH_EXCLUDED(channel)                (0 << channel)
#define PPI_CHG_CH_Excluded(channel)                (0 << channel)
#define PPI_CHG_CH_INCLUDED(channel)                (1 << channel)
#define PPI_CHG_CH_Included(channel)                (1 << channel)
#define PPI_CHG_CH0_EXCLUDED                        (0 << 0)
#define PPI_CHG_CH0_Excluded                        (0 << 0)
#define PPI_CHG_CH0_INCLUDED                        (1 << 0)
#define PPI_CHG_CH0_Included                        (1 << 0)
#define PPI_CHG_CH1_EXCLUDED                        (0 << 1)
#define PPI_CHG_CH1_Excluded                        (0 << 1)
#define PPI_CHG_CH1_INCLUDED                        (1 << 1)
#define PPI_CHG_CH1_Included                        (1 << 1)
#define PPI_CHG_CH2_EXCLUDED                        (0 << 2)
#define PPI_CHG_CH2_Excluded                        (0 << 2)
#define PPI_CHG_CH2_INCLUDED                        (1 << 2)
#define PPI_CHG_CH2_Included                        (1 << 2)
#define PPI_CHG_CH3_EXCLUDED                        (0 << 3)
#define PPI_CHG_CH3_Excluded                        (0 << 3)
#define PPI_CHG_CH3_INCLUDED                        (1 << 3)
#define PPI_CHG_CH3_Included                        (1 << 3)
#define PPI_CHG_CH4_EXCLUDED                        (0 << 4)
#define PPI_CHG_CH4_Excluded                        (0 << 4)
#define PPI_CHG_CH4_INCLUDED                        (1 << 4)
#define PPI_CHG_CH4_Included                        (1 << 4)
#define PPI_CHG_CH5_EXCLUDED                        (0 << 5)
#define PPI_CHG_CH5_Excluded                        (0 << 5)
#define PPI_CHG_CH5_INCLUDED                        (1 << 5)
#define PPI_CHG_CH5_Included                        (1 << 5)
#define PPI_CHG_CH6_EXCLUDED                        (0 << 6)
#define PPI_CHG_CH6_Excluded                        (0 << 6)
#define PPI_CHG_CH6_INCLUDED                        (1 << 6)
#define PPI_CHG_CH6_Included                        (1 << 6)
#define PPI_CHG_CH7_EXCLUDED                        (0 << 7)
#define PPI_CHG_CH7_Excluded                        (0 << 7)
#define PPI_CHG_CH7_INCLUDED                        (1 << 7)
#define PPI_CHG_CH7_Included                        (1 << 7)
#define PPI_CHG_CH8_EXCLUDED                        (0 << 8)
#define PPI_CHG_CH8_Excluded                        (0 << 8)
#define PPI_CHG_CH8_INCLUDED                        (1 << 8)
#define PPI_CHG_CH8_Included                        (1 << 8)
#define PPI_CHG_CH9_EXCLUDED                        (0 << 9)
#define PPI_CHG_CH9_Excluded                        (0 << 9)
#define PPI_CHG_CH9_INCLUDED                        (1 << 9)
#define PPI_CHG_CH9_Included                        (1 << 9)
#define PPI_CHG_CH10_EXCLUDED                       (0 << 10)
#define PPI_CHG_CH10_Excluded                       (0 << 10)
#define PPI_CHG_CH10_INCLUDED                       (1 << 10)
#define PPI_CHG_CH10_Included                       (1 << 10)
#define PPI_CHG_CH11_EXCLUDED                       (0 << 11)
#define PPI_CHG_CH11_Excluded                       (0 << 11)
#define PPI_CHG_CH11_INCLUDED                       (1 << 11)
#define PPI_CHG_CH11_Included                       (1 << 11)
#define PPI_CHG_CH12_EXCLUDED                       (0 << 12)
#define PPI_CHG_CH12_Excluded                       (0 << 12)
#define PPI_CHG_CH12_INCLUDED                       (1 << 12)
#define PPI_CHG_CH12_Included                       (1 << 12)
#define PPI_CHG_CH13_EXCLUDED                       (0 << 13)
#define PPI_CHG_CH13_Excluded                       (0 << 13)
#define PPI_CHG_CH13_INCLUDED                       (1 << 13)
#define PPI_CHG_CH13_Included                       (1 << 13)
#define PPI_CHG_CH14_EXCLUDED                       (0 << 14)
#define PPI_CHG_CH14_Excluded                       (0 << 14)
#define PPI_CHG_CH14_INCLUDED                       (1 << 14)
#define PPI_CHG_CH14_Included                       (1 << 14)
#define PPI_CHG_CH15_EXCLUDED                       (0 << 15)
#define PPI_CHG_CH15_Excluded                       (0 << 15)
#define PPI_CHG_CH15_INCLUDED                       (1 << 15)
#define PPI_CHG_CH15_Included                       (1 << 15)
#define PPI_CHG_CH16_EXCLUDED                       (0 << 16)
#define PPI_CHG_CH16_Excluded                       (0 << 16)
#define PPI_CHG_CH16_INCLUDED                       (1 << 16)
#define PPI_CHG_CH16_Included                       (1 << 16)
#define PPI_CHG_CH17_EXCLUDED                       (0 << 17)
#define PPI_CHG_CH17_Excluded                       (0 << 17)
#define PPI_CHG_CH17_INCLUDED                       (1 << 17)
#define PPI_CHG_CH17_Included                       (1 << 17)
#define PPI_CHG_CH18_EXCLUDED                       (0 << 18)
#define PPI_CHG_CH18_Excluded                       (0 << 18)
#define PPI_CHG_CH18_INCLUDED                       (1 << 18)
#define PPI_CHG_CH18_Included                       (1 << 18)
#define PPI_CHG_CH19_EXCLUDED                       (0 << 19)
#define PPI_CHG_CH19_Excluded                       (0 << 19)
#define PPI_CHG_CH19_INCLUDED                       (1 << 19)
#define PPI_CHG_CH19_Included                       (1 << 19)
#define PPI_CHG_CH20_EXCLUDED                       (0 << 20)
#define PPI_CHG_CH20_Excluded                       (0 << 20)
#define PPI_CHG_CH20_INCLUDED                       (1 << 20)
#define PPI_CHG_CH20_Included                       (1 << 20)
#define PPI_CHG_CH21_EXCLUDED                       (0 << 21)
#define PPI_CHG_CH21_Excluded                       (0 << 21)
#define PPI_CHG_CH21_INCLUDED                       (1 << 21)
#define PPI_CHG_CH21_Included                       (1 << 21)
#define PPI_CHG_CH22_EXCLUDED                       (0 << 22)
#define PPI_CHG_CH22_Excluded                       (0 << 22)
#define PPI_CHG_CH22_INCLUDED                       (1 << 22)
#define PPI_CHG_CH22_Included                       (1 << 22)
#define PPI_CHG_CH23_EXCLUDED                       (0 << 23)
#define PPI_CHG_CH23_Excluded                       (0 << 23)
#define PPI_CHG_CH23_INCLUDED                       (1 << 23)
#define PPI_CHG_CH23_Included                       (1 << 23)
#define PPI_CHG_CH24_EXCLUDED                       (0 << 24)
#define PPI_CHG_CH24_Excluded                       (0 << 24)
#define PPI_CHG_CH24_INCLUDED                       (1 << 24)
#define PPI_CHG_CH24_Included                       (1 << 24)
#define PPI_CHG_CH25_EXCLUDED                       (0 << 25)
#define PPI_CHG_CH25_Excluded                       (0 << 25)
#define PPI_CHG_CH25_INCLUDED                       (1 << 25)
#define PPI_CHG_CH25_Included                       (1 << 25)
#define PPI_CHG_CH26_EXCLUDED                       (0 << 26)
#define PPI_CHG_CH26_Excluded                       (0 << 26)
#define PPI_CHG_CH26_INCLUDED                       (1 << 26)
#define PPI_CHG_CH26_Included                       (1 << 26)
#define PPI_CHG_CH27_EXCLUDED                       (0 << 27)
#define PPI_CHG_CH27_Excluded                       (0 << 27)
#define PPI_CHG_CH27_INCLUDED                       (1 << 27)
#define PPI_CHG_CH27_Included                       (1 << 27)
#define PPI_CHG_CH28_EXCLUDED                       (0 << 28)
#define PPI_CHG_CH28_Excluded                       (0 << 28)
#define PPI_CHG_CH28_INCLUDED                       (1 << 28)
#define PPI_CHG_CH28_Included                       (1 << 28)
#define PPI_CHG_CH29_EXCLUDED                       (0 << 29)
#define PPI_CHG_CH29_Excluded                       (0 << 29)
#define PPI_CHG_CH29_INCLUDED                       (1 << 29)
#define PPI_CHG_CH29_Included                       (1 << 29)
#define PPI_CHG_CH30_EXCLUDED                       (0 << 30)
#define PPI_CHG_CH30_Excluded                       (0 << 30)
#define PPI_CHG_CH30_INCLUDED                       (1 << 30)
#define PPI_CHG_CH30_Included                       (1 << 30)
#define PPI_CHG_CH31_EXCLUDED                       (0 << 31)
#define PPI_CHG_CH31_Excluded                       (0 << 31)
#define PPI_CHG_CH31_INCLUDED                       (1 << 31)
#define PPI_CHG_CH31_Included                       (1 << 31)
/**@}*/

/* --- Function prototypes ------------------------------------------------- */

BEGIN_DECLS

//funktion();
//funktion();
//funktion();
//funktion();

END_DECLS

/**@}*/

#endif
/** @cond */
#else
#warning "ppi_common.h should not be included explicitly, only via ppi.h"
#endif
/** @endcond */

